// Read-only candidate document catalog. Never exposes hidden runtime, credentials or nested checkouts.
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';
import {isNestedCheckout} from './lib/mjs-files.mjs';import {getCareerOpsRoot} from './path-resolver.mjs';import {isMainModule} from './lib/is-main-module.mjs';
const extensions=new Set(['.md','.txt','.yml','.yaml','.tsv','.csv','.json','.html','.pdf','.docx','.doc','.rtf']);
const areas=new Set(['config','modes','data','reports','output','documents','interview-prep','writing-samples','jds']);
const roots=new Set(['cv.md','article-digest.md','voice-dna.md','portals.yml']);
const excluded=new Set(['cache','node_modules','backups','backup','reboot-checkpoints','merged','tracker-additions','__pycache__']);
const secret=/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|\b(?:sk-proj-|sk-ant-api\w*-)[A-Za-z0-9_-]{12,}|^\s*(?:api_key|access_token|client_secret|password)\s*[:=]\s*["']?[A-Za-z0-9_+/=-]{12,}/im;
const hash=s=>createHash('sha256').update(s).digest('hex');
const textFile=p=>!['.pdf','.docx','.doc','.rtf'].includes(path.extname(p).toLowerCase());
export function documentType(p){if(p.startsWith('data/search-reports/'))return 'Search reports';if(p.startsWith('reports/')||p.startsWith('jds/'))return 'Job evaluations';if(p.startsWith('output/'))return 'Application documents';if(p.startsWith('documents/'))return 'Supporting documents';if(p.startsWith('interview-prep/'))return 'Interview preparation';if(p==='cv.md'||p.startsWith('config/')||p.startsWith('modes/')||['article-digest.md','voice-dna.md','portals.yml'].includes(p))return 'Profile and CV';return 'Job-search records';}
function allowed(p){const parts=p.split('/');return !parts.some(x=>x.startsWith('.')||excluded.has(x)||/migration|backup|credentials|secrets|receipt/i.test(x))&&extensions.has(path.extname(p).toLowerCase())&&(parts.length===1?(roots.has(p)||['.pdf','.docx','.doc','.rtf'].includes(path.extname(p).toLowerCase())):areas.has(parts[0]));}
export function documentCatalog(root,candidate){if(!['brad','steve'].includes(candidate))throw new Error('Unknown candidate');const base=fs.realpathSync(root),documents=[];let omitted=0;
 function visit(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,e.name),rel=path.relative(base,file).split(path.sep).join('/');if(e.name.startsWith('.')||excluded.has(e.name)||/migration|backup|credentials|secrets|receipt/i.test(e.name))continue;if(e.isSymbolicLink()){omitted++;continue;}if(e.isDirectory()){if(isNestedCheckout(file)){omitted++;continue;}if(rel.includes('/')||areas.has(rel))visit(file);continue;}if(!e.isFile()||!allowed(rel))continue;const stat=fs.statSync(file);if(stat.size>20*1024*1024){omitted++;continue;}if(textFile(rel)&&secret.test(fs.readFileSync(file,'utf8'))){omitted++;continue;}documents.push({id:hash(candidate+':current:'+rel),path:rel,source:'current',type:documentType(rel),modifiedAt:stat.mtime.toISOString(),size:stat.size,extension:path.extname(rel).slice(1)});}}
 visit(base);const index=path.join(base,'.hosted/document-archive-index.json');let archiveAvailable=false;if(fs.existsSync(index)){if(!fs.realpathSync(index).startsWith(base+path.sep))throw new Error('Archive index escapes root');const archive=JSON.parse(fs.readFileSync(index,'utf8'));if(archive.candidate!==candidate)throw new Error('Foreign archive index');archiveAvailable=true;for(const d of archive.documents||[]){if(!allowed(d.path))continue;const expected='/'+candidate+'/files/'+d.path.split('/').map(encodeURIComponent).join('/');if(d.href!==expected)throw new Error('Invalid archive link');documents.push({...d,id:hash(candidate+':archive:'+d.path),source:'archive',type:documentType(d.path),snapshotAt:archive.snapshotAt});}}
 documents.sort((a,b)=>b.modifiedAt.localeCompare(a.modifiedAt)||a.path.localeCompare(b.path));return {candidate,documents,omitted,archiveAvailable,updatedAt:new Date().toISOString()};}
export function readDocument(root,candidate,id){if(!/^[a-f0-9]{64}$/.test(id||''))throw new Error('Invalid document identifier');const d=documentCatalog(root,candidate).documents.find(x=>x.id===id&&x.source==='current');if(!d)throw new Error('Current document not found');const base=fs.realpathSync(root),file=path.join(base,d.path);if(fs.lstatSync(file).isSymbolicLink()||!fs.realpathSync(file).startsWith(base+path.sep))throw new Error('Document escapes root');const data=fs.readFileSync(file);if(data.length>20*1024*1024||(textFile(d.path)&&secret.test(data.toString('utf8'))))throw new Error('Document cannot be displayed');return {...d,data:data.toString('base64')};}
if(isMainModule(import.meta.url)){try{const root=getCareerOpsRoot(),candidate=process.argv[2];process.stdout.write(JSON.stringify(process.argv[3]?readDocument(root,candidate,process.argv[3]):documentCatalog(root,candidate)));}catch(e){console.error(e.message);process.exitCode=1;}}
