import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';import {randomUUID} from 'node:crypto';
import {publicBoard,snapshot,rankOffers,atomicJSON,jobDir,readJob,searchState,startSearch,cancelSearch,publishSelected,cleanEnvironment,saveReceipt} from '../../src/lib/hosted/search.mjs';
import {candidateExport} from '../../src/lib/hosted/export.mjs';import {lock} from '../../src/lib/hosted/store.mjs';
const code=path.resolve(import.meta.dirname,'../../..');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'career-search-fictional-'));for(const d of ['config','modes','data'])fs.mkdirSync(path.join(root,d));fs.writeFileSync(path.join(root,'cv.md'),'# Fictional CV\n');fs.writeFileSync(path.join(root,'config/profile.yml'),'target_roles:\n  primary: [Senior Frontend Engineer]\nlocation:\n  country: US\n');fs.writeFileSync(path.join(root,'modes/_profile.md'),'# Fictional narrative\n');fs.writeFileSync(path.join(root,'portals.yml'),'tracked_companies:\n  - name: Fictional\n    careers_url: https://job-boards.greenhouse.io/fictional\n');fs.writeFileSync(path.join(root,'data/applications.md'),'# Applications\n');return {root,code,candidate:'brad'};}
const cleanup=c=>fs.rmSync(c.root,{recursive:true,force:true});
function completed(c){const id=randomUUID(),offers=rankOffers([{url:'https://job-boards.greenhouse.io/fictional/jobs/1',company:'Fictional',title:'Senior Frontend Engineer',location:'Remote',source:'greenhouse-api'}],['Senior Frontend Engineer']);const j={id,key:randomUUID(),candidate:c.candidate,revision:snapshot(c).revision,startedAt:new Date().toISOString(),status:'completed',sources:[],counts:{found:1,filtered:0,duplicates:0},offers,selected:[]};saveReceipt(c,j);return j;}
test('public boards reconstruct fixed API destinations and reject executable/private/custom entries',()=>{const b=publicBoard({name:'Demo',careers_url:'https://jobs.ashbyhq.com/demo',parser:{command:'bad'},headers:{secret:'bad'}});assert.equal(b.api,'https://api.ashbyhq.com/posting-api/job-board/demo?includeCompensation=true');assert.equal(b.parser,undefined);assert.equal(b.headers,undefined);for(const url of ['http://jobs.ashbyhq.com/demo','https://127.0.0.1/jobs','https://api.lever.co.evil.test/v0/postings/demo','https://jobs.ashbyhq.com:443/demo','https://jobs.ashbyhq.com/%2e%2e','https://user:secret@jobs.ashbyhq.com/demo']){if(url.includes(':443'))continue;assert.throws(()=>publicBoard({name:'Bad',api:url}));}});
test('snapshot rejects malformed profile and out-of-root sources without resets',()=>{const c=fixture();try{fs.writeFileSync(path.join(c.root,'config/profile.yml'),'broken: [');assert.throws(()=>snapshot(c),/malformed/);fs.writeFileSync(path.join(c.root,'config/profile.yml'),'target_roles:\n  primary: [Engineer]\n');fs.rmSync(path.join(c.root,'portals.yml'));fs.symlinkSync(path.join(code,'package.json'),path.join(c.root,'portals.yml'));assert.throws(()=>snapshot(c),/leaves its workspace/);}finally{cleanup(c);}});
test('preliminary fit retains unknown salary and sanitizes unsafe links',()=>{const ranked=rankOffers([{url:'https://jobs.ashbyhq.com/demo/1',title:'Frontend Engineer',company:'Demo'},{url:'javascript:alert(1)',title:'Engineer'}],['Frontend Engineer']);assert.equal(ranked.length,1);assert.equal(ranked[0].fit.band,'strong');assert.ok(ranked[0].unknown.includes('Compensation'));assert.equal(ranked[0].salary,null);});
test('saved results survive rereads, mark profile drift and reject foreign result selection',()=>{const c=fixture();try{const j=completed(c);assert.equal(searchState(c,j.id).run.offers.length,1);fs.appendFileSync(path.join(c.root,'cv.md'),'Changed\n');assert.equal(searchState(c,j.id).run.outdated,true);assert.throws(()=>publishSelected(c,{id:j.id,ids:['invented']}));assert.throws(()=>publishSelected({...c,candidate:'steve'},{id:j.id,ids:[j.offers[0].id]}),/another workspace/);}finally{cleanup(c);}});
test('canonical selection reconciles interruption without pipeline/history duplicates or tracker writes',()=>{const c=fixture();try{const j=completed(c),ids=[j.offers[0].id];const before=fs.readFileSync(path.join(c.root,'data/applications.md'),'utf8');assert.equal(publishSelected(c,{id:j.id,ids}).added,1);assert.equal(publishSelected(c,{id:j.id,ids}).added,0);const saved=readJob(c,j.id);saved.selected=[];atomicJSON(path.join(jobDir(c,j.id),'receipt.json'),saved);assert.equal(publishSelected(c,{id:j.id,ids}).added,0);assert.equal(fs.readFileSync(path.join(c.root,'data/pipeline.md'),'utf8').split(j.offers[0].url).length,2);assert.equal(fs.readFileSync(path.join(c.root,'data/scan-history.tsv'),'utf8').split(j.offers[0].url).length,2);assert.equal(fs.readFileSync(path.join(c.root,'data/applications.md'),'utf8'),before);}finally{cleanup(c);}});
test('publication respects edit lock and current blacklist',()=>{const c=fixture();try{const j=completed(c);lock(c.root,()=>assert.throws(()=>publishSelected(c,{id:j.id,ids:[j.offers[0].id]}),/progress/));fs.writeFileSync(path.join(c.root,'data/blacklist.md'),'| Company | Since | Scope | Reason |\n|---|---|---|---|\n| Fictional | 2026-10-01 | all | owner |\n');assert.throws(()=>publishSelected(c,{id:j.id,ids:[j.offers[0].id]}),/now blacklisted/);assert.equal(fs.existsSync(path.join(c.root,'data/pipeline.md')),false);}finally{cleanup(c);}});
test('exports exclude caches and include readable reports; backup refuses pending publication',()=>{const c=fixture();try{const j=completed(c);fs.mkdirSync(path.join(c.root,'data/cache'),{recursive:true});fs.writeFileSync(path.join(c.root,'data/cache/private'),'cache');fs.mkdirSync(path.join(jobDir(c,j.id),'runtime'),{recursive:true});fs.writeFileSync(path.join(jobDir(c,j.id),'runtime/changing'),'runtime');const exported=candidateExport(c);assert.ok(exported.files.some(f=>f.path.startsWith('data/search-reports/')));assert.ok(exported.files.every(f=>!f.path.includes('cache')&&!f.path.includes('runtime')));const out=JSON.parse(execFileSync('python3',[path.join(code,'portal/deploy/candidate-backup.py'),c.root,path.join(c.root,'.hosted/backups'),'--drill'],{encoding:'utf8'}));const manifest=JSON.parse(fs.readFileSync(out.snapshot.replace('.tar.gz','.json'),'utf8'));assert.ok(Object.keys(manifest.files).every(f=>!f.includes('runtime')&&!f.startsWith('data/cache/')));atomicJSON(path.join(jobDir(c,j.id),'publication.json'),{status:'pending'});assert.throws(()=>execFileSync('python3',[path.join(code,'portal/deploy/candidate-backup.py'),c.root,path.join(c.root,'.hosted/backups')],{stdio:'pipe'}));}finally{cleanup(c);}});
test('missing worker is a failed or interrupted run and starts are idempotent',async()=>{const c=fixture();try{c.code=path.join(c.root,'absent-code');const key=randomUUID(),one=startSearch(c,{key}),two=startSearch(c,{key});assert.equal(one.id,two.id);cancelSearch(c,one.id);await new Promise(r=>setTimeout(r,100));const j=readJob(c,one.id);j.startedAt='2000-01-01T00:00:00Z';atomicJSON(path.join(jobDir(c,one.id),'receipt.json'),j);assert.equal(searchState(c,one.id).run.status,'interrupted');}finally{cleanup(c);}});
test('worker environment contains no inherited model credentials or execution options',()=>{process.env.CAREER_SEARCH_TEST_SECRET='must-not-leak';try{const env=cleanEnvironment('/fictional','/code');assert.equal(env.CAREER_SEARCH_TEST_SECRET,undefined);assert.equal(env.NODE_OPTIONS,undefined);assert.equal(env.CAREER_OPS_ROOT,'/fictional');}finally{delete process.env.CAREER_SEARCH_TEST_SECRET;}});

test('retry clears a pending publication after the selected receipt was already saved',()=>{const c=fixture();try{const j=completed(c),ids=[j.offers[0].id];publishSelected(c,{id:j.id,ids});const file=path.join(jobDir(c,j.id),'publication.json'),transaction=JSON.parse(fs.readFileSync(file,'utf8'));transaction.status='pending';atomicJSON(file,transaction);assert.throws(()=>candidateExport(c));assert.equal(publishSelected(c,{id:j.id,ids}).added,0);assert.equal(JSON.parse(fs.readFileSync(file,'utf8')).status,'completed');assert.deepEqual(JSON.parse(fs.readFileSync(file,'utf8')).before,transaction.before);assert.ok(candidateExport(c).files.length>0);}finally{cleanup(c);}});

import {readFilters,saveFilters,filterHistory,existingOpportunities} from '../../src/lib/hosted/search-settings.mjs';
test('filter save preserves unrelated rules, backs up, rejects conflicts and restores',()=>{const c=fixture();try{fs.appendFileSync(path.join(c.root,'portals.yml'),'title_filter:\n  positive: [Engineer]\nsalary_filter:\n  minimum: 125000\nlocation_filter:\n  allow: [Remote]\n  strict: true\n');const first=readFilters(c),before=fs.readFileSync(path.join(c.root,'portals.yml'),'utf8');const next=saveFilters(c,{revision:first.revision,fields:{...first.fields,include:'AI Engineer\nAI Engineer'}});assert.equal(next.fields.include,'AI Engineer');assert.equal(next.otherFilters.salary_filter.minimum,125000);assert.equal(next.locationStrict,true);assert.throws(()=>saveFilters(c,{revision:first.revision,fields:first.fields}),/changed/);assert.throws(()=>saveFilters(c,{revision:next.revision,fields:{...next.fields,include:''}}),/included/);const h=filterHistory(c);assert.equal(h.length,1);const restored=saveFilters(c,{revision:next.revision,restore:h[0].id});assert.equal(restored.revision,first.revision);assert.equal(fs.readFileSync(path.join(c.root,'portals.yml'),'utf8'),before);assert.equal(filterHistory(c).length,2);}finally{cleanup(c);}});
test('filter change marks a saved search outdated without changing its receipt',()=>{const c=fixture();try{const j=completed(c),settings=readFilters(c);saveFilters(c,{revision:settings.revision,fields:{...settings.fields,include:'Different Engineer'}});assert.equal(searchState(c,j.id).run.outdated,true);}finally{cleanup(c);}});
test('existing opportunities deduplicate pipeline/history and never treat skipped jobs as matches',()=>{const c=fixture();try{fs.writeFileSync(path.join(c.root,'data/scan-history.tsv'),'url\tfirst_seen\tportal\ttitle\tcompany\tstatus\tlocation\nhttps://jobs.ashbyhq.com/demo/1\t2026-10-02\tashby\tEngineer\tDemo\tadded\tRemote\nhttps://jobs.ashbyhq.com/demo/2\t2026-10-02\tashby\tEngineer\tDemo\tskipped_location\tLondon\n');fs.writeFileSync(path.join(c.root,'data/pipeline.md'),'- [ ] https://jobs.ashbyhq.com/demo/1 | Demo | Engineer | Remote\n- [x] #003 | https://jobs.ashbyhq.com/demo/3 | Demo | AI Engineer | 4.1/5 | PDF\n- [ ] javascript:alert(1) | Demo | bad\n');const jobs=existingOpportunities(c);assert.equal(jobs.length,2);assert.ok(jobs.some(j=>j.status==='In pipeline'&&j.lastSeen==='2026-10-02'));assert.ok(jobs.some(j=>j.status==='Previously processed'&&j.location==='Unknown'));}finally{cleanup(c);}});
import {repairSources} from '../../../portal/deploy/repair-search-sources.mjs';
test('source repairs are exact, idempotent, preserve filters and back up authoritative configuration',()=>{const c=fixture();try{fs.appendFileSync(path.join(c.root,'portals.yml'),'  - name: RunPod\n    careers_url: https://job-boards.greenhouse.io/runpod\n    api: https://boards-api.greenhouse.io/v1/boards/runpod/jobs\n  - name: Runway\n    careers_url: https://jobs.ashbyhq.com/custom-owner-choice\ntitle_filter:\n  positive: [Engineer]\n');const before=readFilters(c);const r=repairSources(c.root);assert.deepEqual(r.changed,['RunPod']);assert.equal(readFilters(c).fields.include,before.fields.include);assert.match(fs.readFileSync(path.join(c.root,'portals.yml'),'utf8'),/custom-owner-choice/);assert.equal(filterHistory(c).length,1);assert.deepEqual(repairSources(c.root).changed,[]);}finally{cleanup(c);}});
test('advanced filter validation fails before checkpoint or write; owner custom API is retained',()=>{const c=fixture();try{fs.appendFileSync(path.join(c.root,'portals.yml'),'  - name: Temporal\n    careers_url: https://job-boards.greenhouse.io/temporal\n    api: https://api.ashbyhq.com/posting-api/job-board/owner-choice\ntitle_filter:\n  positive: [Engineer]\n');const first=readFilters(c);for(const advanced of ['salary_filter: wrong','salary_filter: {min: 200000, max: 100000}','max_posting_age_days: -1','tracked_companies: []'])assert.throws(()=>saveFilters(c,{revision:first.revision,fields:first.fields,advanced}));assert.equal(filterHistory(c).length,0);assert.equal(readFilters(c).revision,first.revision);assert.deepEqual(repairSources(c.root).changed,[]);}finally{cleanup(c);}});
import {recordOpportunityNote} from '../../src/lib/hosted/search-settings.mjs';
test('user-stated opportunity notes require a saved job, preserve other jobs and checkpoint once',()=>{const c=fixture();try{const url='https://jobs.ashbyhq.com/demo/1';fs.writeFileSync(path.join(c.root,'data/pipeline.md'),'- [ ] '+url+' | Demo | Engineer | Remote\n');const before=fs.readFileSync(path.join(c.root,'data/pipeline.md'),'utf8');assert.throws(()=>recordOpportunityNote(c,'https://jobs.ashbyhq.com/other/2','note'),/saved opportunity/);assert.deepEqual(recordOpportunityNote(c,url,'User reviewed global hiring; specific eligibility unknown.'),{changed:true});assert.equal(existingOpportunities(c)[0].reviewNotes,'User reviewed global hiring; specific eligibility unknown.');assert.deepEqual(recordOpportunityNote(c,url,'User reviewed global hiring; specific eligibility unknown.'),{changed:false});assert.equal(fs.readdirSync(path.join(c.root,'.hosted/opportunity-note-history')).length,1);assert.equal(fs.readFileSync(path.join(c.root,'data/pipeline.md'),'utf8'),before);assert.equal(JSON.parse(fs.readFileSync(path.join(c.root,'data/opportunity-notes.json'),'utf8'))[url].source,'user-stated');}finally{cleanup(c);}});
