import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {newConversation,readConversation,persistConversation,buildAssistantContext,assistantSettings,assistantState,saveAssistantResponse} from '../../src/lib/hosted/assistant.mjs';
import {executeAssistant,applyAssistantAction,parseAssistantReply} from '../../src/lib/hosted/assistant-runner.mjs';
import {save,readState} from '../../src/lib/hosted/store.mjs';import {hostedAllowed} from '../../src/lib/hosted/policy.mjs';
const code=path.resolve(import.meta.dirname,'../../..');
function fixture(candidate='brad'){const root=fs.mkdtempSync(path.join(os.tmpdir(),'career-ai-'));for(const d of ['config','modes','data'])fs.mkdirSync(path.join(root,d));fs.writeFileSync(path.join(root,'cv.md'),'# Fictional Candidate\n\nLed 5 engineers.');fs.writeFileSync(path.join(root,'config/profile.yml'),'candidate:\n  full_name: Fictional Candidate\ntarget_roles:\n  primary: [Engineer]\n');fs.writeFileSync(path.join(root,'modes/_profile.md'),'# Fictional targeting');fs.writeFileSync(path.join(root,'data/applications.md'),'# Tracker');return {candidate,root,code};}
function setup(c,mode='chat',message='Help with my career'){const d=newConversation(c),key=randomUUID();d.messages.push({role:'user',content:message,key});d.run={id:key,status:'queued',mode,partial:''};persistConversation(c,d);const input={context:buildAssistantContext(c),mode,message,messages:d.messages,operationId:Date.now()+'-'+key};fs.writeFileSync(path.join(c.root,'.hosted/assistant',d.id,'input-'+key+'.json'),JSON.stringify(input));return {d,key,input};}
function stream(text){return new Response(new ReadableStream({start(controller){for(const part of [text.slice(0,20),text.slice(20)])controller.enqueue(new TextEncoder().encode('data: '+JSON.stringify({choices:[{delta:{content:part}}]})+'\n\n'));controller.enqueue(new TextEncoder().encode('data: [DONE]\n\n'));controller.close();}}));}
const env={CAREER_OPS_AI_URL:'http://127.0.0.1:18791/v1/chat/completions',CAREER_OPS_AI_TOKEN:'fictional-private-token'};
test('transport is private, disabled by default, no raw worker routes and configured fallback status',()=>{assert.equal(assistantSettings({}).enabled,false);assert.throws(()=>assistantSettings({...env,CAREER_OPS_ASSISTANT_ENABLED:'1',CAREER_OPS_AI_URL:'https://external.test/v1/chat/completions'}));assert.equal(assistantSettings({...env,CAREER_OPS_ASSISTANT_ENABLED:'1'}).paidFallback,true);assert.equal(hostedAllowed('/api/hosted/assistant','POST'),true);assert.equal(hostedAllowed('/api/run','POST'),false);});
test('candidate conversation isolation and arbitrary identifiers fail closed',()=>{const c=fixture();try{const d=newConversation(c);assert.throws(()=>readConversation({...c,candidate:'steve'},d.id),/another workspace/);assert.throws(()=>readConversation(c,'../../profile'),/Invalid/);assert.equal(assistantState(c,d.id,{}).conversation.candidate,'brad');}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('streamed reply is persisted and gateway receives a fixed agent, thread and no tools',async()=>{const c=fixture();try{const {d,key}=setup(c);let body;await executeAssistant(c,d.id,key,{env,fetchImpl:async(_url,opt)=>{body=JSON.parse(opt.body);return stream('Your primary CV records leadership of 5 engineers.');}});const result=readConversation(c,d.id);assert.equal(result.run.status,'completed');assert.equal(result.messages.at(-1).role,'assistant');assert.equal(body.model,'openclaw/career-brad');assert.equal(body.user,'careerops:brad:'+d.id);assert.equal(body.tools,undefined);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('drafts appear under candidate output and duplicate operations preserve bytes',async()=>{const c=fixture();try{const {d,key,input}=setup(c,'draft','Draft my resume using current CV.');const content='Led 5 engineers.';await executeAssistant(c,d.id,key,{env,fetchImpl:async()=>stream('Draft prepared.\n<career-action>'+JSON.stringify({type:'draft',content})+'</career-action>')});const result=readConversation(c,d.id);assert.equal(result.run.status,'completed');const file=path.join(c.root,result.run.result.path),before=fs.readFileSync(file);applyAssistantAction(c,{id:key,conversationId:d.id},input,{type:'draft',content});assert.deepEqual(fs.readFileSync(file),before);assert.ok(file.includes('/output/assistant/'));}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('unrequested writes, unsupported numbers, unknown fields and arbitrary draft paths are rejected',()=>{const c=fixture();try{const {d,key,input}=setup(c);assert.throws(()=>applyAssistantAction(c,{id:key,conversationId:d.id},input,{type:'cv',content:'Changed CV'}),/not requested/);input.mode='draft';assert.throws(()=>applyAssistantAction(c,{id:key,conversationId:d.id},input,{type:'draft',content:'Led 900 engineers.'}),/unsupported number/);assert.throws(()=>applyAssistantAction(c,{id:key,conversationId:d.id},input,{type:'draft',content:'CV',path:'../steve/cv.md'}),/unsupported fields/);assert.throws(()=>parseAssistantReply('reply\n<career-action>broken</career-action>'),/invalid change/);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('explicit CV save is backed up, exactly-once recovery survives changed revision and conflicts retain current work',()=>{const c=fixture();try{const {d,key,input}=setup(c,'cv','Rephrase my current CV.');const run={id:key,conversationId:d.id},action={type:'cv',content:'# Fictional Candidate\n\nManaged 5 engineers.'};applyAssistantAction(c,run,input,action);assert.equal(fs.readFileSync(path.join(c.root,'cv.md'),'utf8'),action.content);assert.ok(applyAssistantAction(c,run,input,action).recovered);const newer=setup(c,'cv','Another edit');const state=readState(c);save(c,{action:'cv',revision:state.revision,content:'# Independently saved CV'});assert.throws(()=>applyAssistantAction(c,{id:newer.key,conversationId:newer.d.id},newer.input,{type:'cv',content:'# Changed CV'}),/changed/);assert.equal(fs.readFileSync(path.join(c.root,'cv.md'),'utf8'),'# Independently saved CV');}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('cancellation prevents proposed saves and provider errors never disclose credentials',async()=>{const c=fixture();try{const {d,key}=setup(c,'cv');fs.writeFileSync(path.join(c.root,'.hosted/assistant',d.id,'cancel-'+key+'.json'),'{}');await executeAssistant(c,d.id,key,{env,fetchImpl:async()=>stream('Change\n<career-action>{"type":"cv","content":"# Changed"}</career-action>')});assert.equal(readConversation(c,d.id).run.status,'cancelled');assert.match(fs.readFileSync(path.join(c.root,'cv.md'),'utf8'),/Fictional/);const next=setup(c);await executeAssistant(c,next.d.id,next.key,{env,fetchImpl:async()=>{throw new Error(env.CAREER_OPS_AI_TOKEN);}});assert.equal(readConversation(c,next.d.id).run.status,'failed');assert.ok(!JSON.stringify(readConversation(c,next.d.id)).includes(env.CAREER_OPS_AI_TOKEN));}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('interrupted CV commit is recovered without replay and an unknown dead run becomes retryable',()=>{const c=fixture();try{const {d,key,input}=setup(c,'cv','Rephrase existing CV.');d.run={...d.run,status:'saving',operationId:input.operationId,pid:99999999,startedAt:'2020-01-01T00:00:00Z',partial:'Rephrased existing CV.'};persistConversation(c,d);applyAssistantAction(c,{id:key,conversationId:d.id},input,{type:'cv',content:'# Fictional Candidate\n\nManaged 5 engineers.'});const recovered=assistantState(c,d.id,{}).conversation;assert.equal(recovered.run.status,'completed');assert.equal(recovered.run.result.recovered,true);assert.equal(assistantState(c,d.id,{}).conversation.messages.length,recovered.messages.length);const next=setup(c);next.d.run={...next.d.run,pid:99999999,startedAt:'2020-01-01T00:00:00Z'};persistConversation(c,next.d);assert.equal(assistantState(c,next.d.id,{}).conversation.run.status,'interrupted');}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('linked conversation roots and files are rejected before reading or writing',()=>{const c=fixture(),outside=fs.mkdtempSync(path.join(os.tmpdir(),'career-ai-outside-'));try{const d=newConversation(c),file=path.join(c.root,'.hosted/assistant',d.id,'conversation.json');const contents=fs.readFileSync(file);fs.writeFileSync(path.join(outside,'conversation.json'),contents);fs.unlinkSync(file);fs.symlinkSync(path.join(outside,'conversation.json'),file);assert.throws(()=>readConversation(c,d.id),/leaves/);fs.rmSync(path.join(c.root,'.hosted/assistant'),{recursive:true});fs.symlinkSync(outside,path.join(c.root,'.hosted/assistant'));assert.throws(()=>newConversation(c),/leaves/);}finally{fs.rmSync(c.root,{recursive:true,force:true});fs.rmSync(outside,{recursive:true,force:true});}});
test('profile edits use canonical history and preserve the CV; secret-bearing primary sources are not sent',()=>{const c=fixture();try{const {d,key,input}=setup(c,'profile','My location is Grand Rapids.');applyAssistantAction(c,{id:key,conversationId:d.id},input,{type:'profile',fields:{location:'Grand Rapids'}});assert.equal(readState(c).profile.candidate.location,'Grand Rapids');assert.match(fs.readFileSync(path.join(c.root,'cv.md'),'utf8'),/Led 5/);fs.writeFileSync(path.join(c.root,'cv.md'),'password: abcdefghijklmnopqrstuvwxyz');assert.throws(()=>buildAssistantContext(c),/restricted/);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('a freshly spawned run gets a startup grace period before dead-worker recovery',()=>{const c=fixture();try{const {d}=setup(c);d.run={...d.run,startedAt:new Date().toISOString(),pid:99999999};persistConversation(c,d);assert.equal(assistantState(c,d.id,{}).conversation.run.status,'queued');}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('worker checkpoints retry temporary workspace lock contention instead of losing the reply',async()=>{const c=fixture();try{const {d,key}=setup(c);const file=path.join(c.root,'.hosted/edit.lock');fs.writeFileSync(file,JSON.stringify({pid:process.pid}));setTimeout(()=>fs.rmSync(file,{force:true}),120);await executeAssistant(c,d.id,key,{env,fetchImpl:async()=>stream('A retained source-backed reply.')});assert.equal(readConversation(c,d.id).run.status,'completed');}finally{fs.rmSync(c.root,{recursive:true,force:true});}});

test('save completed response verbatim, retry once, retain edited file and isolate candidate',()=>{const c=fixture();try{const d=newConversation(c);d.messages=[{role:'user',content:'Ask questions'},{role:'assistant',content:'## Questions\n\nWhat changed since 2024?'}];persistConversation(c,d);assert.throws(()=>saveAssistantResponse(c,{id:d.id,index:0}),/completed/);assert.throws(()=>saveAssistantResponse({...c,candidate:'steve'},{id:d.id,index:1}),/another workspace/);const saved=saveAssistantResponse(c,{id:d.id,index:1});const file=path.join(c.root,saved.messages[1].savedResponse.path),bytes=fs.readFileSync(file,'utf8');assert.match(bytes,/What changed since 2024/);assert.match(bytes,/not a verified source/);assert.equal(saveAssistantResponse(c,{id:d.id,index:1}).messages[1].savedResponse.documentId,saved.messages[1].savedResponse.documentId);assert.equal(fs.readFileSync(file,'utf8'),bytes);assert.equal(fs.readdirSync(path.dirname(file)).length,1);fs.writeFileSync(file,'Owner edit');assert.throws(()=>saveAssistantResponse(c,{id:d.id,index:1}),/without overwriting/);assert.equal(fs.readFileSync(file,'utf8'),'Owner edit');}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('save response rejects linked output before writing outside workspace',()=>{const c=fixture(),outside=fs.mkdtempSync(path.join(os.tmpdir(),'career-response-outside-'));try{const d=newConversation(c);d.messages=[{role:'assistant',content:'A response.'}];persistConversation(c,d);fs.symlinkSync(outside,path.join(c.root,'output'));assert.throws(()=>saveAssistantResponse(c,{id:d.id,index:0}),/leaves/);assert.equal(fs.readdirSync(outside).length,0);}finally{fs.rmSync(c.root,{recursive:true,force:true});fs.rmSync(outside,{recursive:true,force:true});}});
