import {execFileSync} from 'node:child_process';import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {readState,save,history,prepareNarrative,updateTracker} from '../../src/lib/hosted/store.mjs';import {hostedAllowed,hostedConfig} from '../../src/lib/hosted/policy.mjs';
const code=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'hosted-test-'));fs.mkdirSync(path.join(root,'config'));fs.mkdirSync(path.join(root,'modes'));fs.mkdirSync(path.join(root,'data'));fs.writeFileSync(path.join(root,'cv.md'),'# Fictional Person\n');fs.writeFileSync(path.join(root,'config/profile.yml'),'candidate:\n  full_name: Fictional Person\ncompensation:\n  minimum: $100K\n  target_range: $150K\nnarrative:\n  evidence: Keep this field\n');fs.writeFileSync(path.join(root,'modes/_profile.md'),'# Narrative\n\n## Compensation\n\n$100K minimum.\n\n## Evidence\n\nConfirmed examples only.\n');fs.writeFileSync(path.join(root,'data/applications.md'),'# Applications\n\n| # | Date | Company | Role | Score | Status | PDF | Report | Notes |\n|---|---|---|---|---|---|---|---|---|\n| 1 | 2026-10-02 | Fictional Co | Engineer | 4.0/5 | Evaluated | ❌ | — | baseline |\n');return {root,code,candidate:'brad'};}
test('hosted policy rejects upstream API families and wrong root config',()=>{for(const p of ['/api/run','/api/assistant','/api/apply/fill','/api/explore','/api/tracker/delete','/api/cv/ingest','/config'])assert.equal(hostedAllowed(p,'POST'),false);assert.equal(hostedAllowed('/api/hosted','POST'),true);assert.throws(()=>hostedConfig({CAREER_OPS_HOSTED:'1',CAREER_OPS_CANDIDATE:'../steve'}));});
test('CV stale save rejected, history restores and unrelated YAML survives',()=>{const c=fixture();try{const first=readState(c);save(c,{action:'cv',revision:first.revision,content:'# Revised\n'});assert.throws(()=>save(c,{action:'cv',revision:first.revision,content:'stale'}),e=>e.status===409);const current=readState(c);const h=history(c)[0];save(c,{action:'restore',revision:current.revision,id:h.id});assert.equal(readState(c).contents['cv.md'],'# Fictional Person\n');assert.equal(history(c).length,2);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('first profile save automatically synchronizes targeting and preserves evidence',()=>{const c=fixture();try{let state=readState(c);const proposed=prepareNarrative(state.profile,state.contents['modes/_profile.md']);assert.match(proposed.proposed,/Confirmed examples/);assert.equal(proposed.removed.length,1);const fields={name:'Fictional Person',email:'f@example.test',phone:'',location:'Test city',roles:'Engineer',minimum:'$120K base',target:'$160K base',currency:'USD',remote:'Remote',authorization:'Authorized',citizenship:'',sponsorship:false};save(c,{action:'profile',revision:state.revision,fields,narrative:state.contents['modes/_profile.md']});state=readState(c);assert.equal(state.profile.narrative.evidence,'Keep this field');assert.equal(state.profile.compensation.minimum,'$120K base');assert.match(state.contents['modes/_profile.md'],/Base minimum: \$120K base/);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('canonical tracker updates ledger, rejects stale revision and preserves notes',()=>{const c=fixture();try{const state=readState(c);updateTracker(c,{n:'1',status:'Applied',note:'human confirmed',trackerRevision:state.trackerRevision});assert.match(fs.readFileSync(path.join(c.root,'data/status-log.tsv'),'utf8'),/Evaluated\tApplied\tweb/);assert.match(fs.readFileSync(path.join(c.root,'data/applications.md'),'utf8'),/baseline; human confirmed/);assert.throws(()=>updateTracker(c,{n:'1',status:'Interview',note:'',trackerRevision:state.trackerRevision}),e=>e.status===409);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('malformed profile refuses reset',()=>{const c=fixture();try{fs.writeFileSync(path.join(c.root,'config/profile.yml'),'[broken');assert.throws(()=>readState(c),e=>e.status===409);assert.equal(fs.readFileSync(path.join(c.root,'config/profile.yml'),'utf8'),'[broken');}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('source symlink cannot leave the fixed candidate root',()=>{const c=fixture();try{fs.rmSync(path.join(c.root,'cv.md'));fs.symlinkSync(path.join(code,'AGENTS.md'),path.join(c.root,'cv.md'));assert.throws(()=>readState(c),e=>e.status===409);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('dead save lock recovers after process restart',()=>{const c=fixture();try{fs.mkdirSync(path.join(c.root,'.hosted'));fs.writeFileSync(path.join(c.root,'.hosted/edit.lock'),JSON.stringify({pid:2147483647}));assert.equal(readState(c).candidate,'brad');}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('framework image/data bypass paths are denied',()=>{for(const p of ['/_next/image','/_next/data/build/config.json'])assert.equal(hostedAllowed(p,'GET'),false);assert.equal(hostedAllowed('/_next/static/chunks/page.js','GET'),true);});
test('interrupted multi-file transaction finishes and records one audit entry',()=>{const c=fixture();try{const state=readState(c);const tx={id:'interrupted-fixture',candidate:'brad',at:new Date().toISOString(),operation:'profile',beforeRevision:state.revision,afterRevision:'fixture',after:{...state.contents,'cv.md':'# Recovered\n'}};fs.writeFileSync(path.join(c.root,'.hosted/pending.json'),JSON.stringify(tx));assert.equal(readState(c).contents['cv.md'],'# Recovered\n');assert.equal(fs.existsSync(path.join(c.root,'.hosted/pending.json')),false);readState(c);assert.equal(fs.readFileSync(path.join(c.root,'.hosted/audit.jsonl'),'utf8').trim().split('\n').length,1);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});

test('core writer checks revision under its own lock',()=>{const c=fixture();try{const state=readState(c);const tracker=path.join(c.root,'data/applications.md');fs.appendFileSync(tracker,'\nChanged after read\n');const before=fs.readFileSync(tracker,'utf8');assert.throws(()=>execFileSync(process.execPath,[path.join(code,'set-status.mjs'),'--row','1','Applied','--expected-revision',state.trackerRevision,'--json'],{env:{...process.env,CAREER_OPS_ROOT:c.root,CAREER_OPS_TRACKER:tracker},stdio:'pipe'}),e=>e.status===3&&String(e.stdout).includes('revision-conflict'));assert.equal(fs.readFileSync(tracker,'utf8'),before);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('checkpoint failure prevents a CV write',()=>{const c=fixture();try{const state=readState(c);fs.writeFileSync(path.join(c.root,'.hosted/revisions'),'blocked');assert.throws(()=>save(c,{action:'cv',revision:state.revision,content:'must not be saved'}));assert.equal(fs.readFileSync(path.join(c.root,'cv.md'),'utf8'),state.contents['cv.md']);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('profile save automatically reconciles duplicate targeting with a recoverable original',()=>{const c=fixture();try{let state=readState(c);const original=state.contents;save(c,{action:'profile',revision:state.revision,fields:{name:'Fictional',email:'',phone:'',location:'',roles:'Engineer',minimum:'$125K',target:'$150K',currency:'USD',remote:'',authorization:'',citizenship:''},narrative:state.contents['modes/_profile.md']+'\n## Your Comp Targets\ncontradiction'});state=readState(c);assert.match(state.contents['modes/_profile.md'],/Base minimum: \$125K/);assert.doesNotMatch(state.contents['modes/_profile.md'],/contradiction/);assert.deepEqual(history(c,history(c)[0].id).contents,original);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
