import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {projectKnowledge,workspaceSnapshot,GUIDE_FILES} from '../../src/lib/hosted/project-context.mjs';
import {digest} from '../../src/lib/hosted/store.mjs';import {assistantPrompt,applyAssistantAction} from '../../src/lib/hosted/assistant-runner.mjs';
const repo=path.resolve(import.meta.dirname,'../../..');
function fixture(){const base=fs.mkdtempSync(path.join(os.tmpdir(),'career-context-'));const root=path.join(base,'brad'),code=path.join(base,'code');fs.mkdirSync(path.join(root,'data'),{recursive:true});fs.mkdirSync(path.join(code,'portal'),{recursive:true});fs.cpSync(path.join(repo,'portal/knowledge'),path.join(code,'portal/knowledge'),{recursive:true});fs.writeFileSync(path.join(root,'portals.yml'),'title_filter:\n  positive: [Engineer]\n');fs.writeFileSync(path.join(root,'data/applications.md'),'| # | Status |\n|---|---|\n| 1 | Interview |\n');fs.writeFileSync(path.join(root,'data/pipeline.md'),'- [ ] https://jobs.example.test/a | Example | Engineer | Remote\n');return {base,root,code,candidate:'brad'};}
test('qualified guides name the deployed repo and reject changed documentation',()=>{const c=fixture();try{const dir=path.join(c.code,'portal/knowledge');const manifest={format:'career-project-knowledge-v1',release:'fictional-release',sourceCommit:'a'.repeat(40),sha256:Object.fromEntries(GUIDE_FILES.map(n=>[n,digest(fs.readFileSync(path.join(dir,n),'utf8'))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest));const knowledge=projectKnowledge(c);assert.match(knowledge.documents['project-overview.md'],/wellbeing0\/career-ops/);assert.equal(knowledge.release,'fictional-release');fs.appendFileSync(path.join(dir,GUIDE_FILES[0]),'unexpected');assert.throws(()=>projectKnowledge(c),/differs/);}finally{fs.rmSync(c.base,{recursive:true,force:true});}});
test('read-only snapshot explains empty search and includes only selected candidate summaries',()=>{const c=fixture();try{const dir=path.join(c.root,'.hosted/search','1'.repeat(36));fs.mkdirSync(dir,{recursive:true});const receipt={candidate:'brad',id:'1'.repeat(36),startedAt:'2026-10-07T00:00:00Z',status:'completed',counts:{found:8,filtered:3,duplicates:5},offers:[],selected:[],sources:[{company:'Example',status:'error',error:'Unavailable'}]};const file=path.join(dir,'receipt.json');fs.writeFileSync(file,JSON.stringify(receipt));const before=fs.readFileSync(file,'utf8');const snapshot=workspaceSnapshot(c,{});assert.equal(snapshot.applications.total,1);assert.equal(snapshot.applications.statusCounts.Interview,1);assert.equal(snapshot.pipeline.total,1);assert.equal(snapshot.searches.latest.counts.duplicates,5);assert.equal(snapshot.searches.latest.sources[0].status,'error');assert.equal(fs.readFileSync(file,'utf8'),before);receipt.candidate='steve';fs.writeFileSync(file,JSON.stringify(receipt));assert.throws(()=>workspaceSnapshot(c,{}),/another candidate/);}finally{fs.rmSync(c.base,{recursive:true,force:true});}});
test('project docs are explanatory context and cannot authorize unsupported resume numbers',()=>{const c=fixture();try{const context={sources:{'cv.md':'Fictional Engineer'},project:projectKnowledge(c),workspace:{candidate:'brad',capturedAt:'2026-10-07',pipeline:{total:12345}},references:[]};const input={context,mode:'draft',messages:[{role:'user',content:'Draft my existing experience'}]};assert.match(assistantPrompt(input,'brad'),/CURRENT WORKSPACE SNAPSHOT/);assert.match(assistantPrompt(input,'brad'),/never candidate facts/);assert.throws(()=>applyAssistantAction(c,{id:'fictional'},input,{type:'draft',content:'Handled 12345 candidates.'}),/unsupported number/);}finally{fs.rmSync(c.base,{recursive:true,force:true});}});
test('linked project guides and linked search receipts cannot read outside approved roots',()=>{const c=fixture();try{const dir=path.join(c.code,'portal/knowledge');fs.rmSync(path.join(dir,GUIDE_FILES[0]));fs.symlinkSync(path.join(c.root,'portals.yml'),path.join(dir,GUIDE_FILES[0]));assert.throws(()=>projectKnowledge(c),/approved root/);const searches=path.join(c.root,'.hosted/search');fs.mkdirSync(path.dirname(searches),{recursive:true});fs.symlinkSync(path.join(c.code,'portal'),searches);assert.throws(()=>workspaceSnapshot(c,{}),/leaves workspace/);}finally{fs.rmSync(c.base,{recursive:true,force:true});}});
