import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {guidedContext,guidedPrompt,saveGuidedReview} from '../../src/lib/hosted/guided-workflows.mjs';
import {newConversation,assistantState,persistConversation,readConversation,buildAssistantContext} from '../../src/lib/hosted/assistant.mjs';
import {executeAssistant,applyAssistantAction} from '../../src/lib/hosted/assistant-runner.mjs';
import {hostedDocuments} from '../../src/lib/hosted/documents.mjs';
const code=path.resolve(import.meta.dirname,'../../..'),jd='This fictional engineering role builds frontend products and leads design reviews. Work includes collaboration with engineering and product managers, testing accessible user interfaces and mentoring other engineers. Remote work is supported within the United States. '.repeat(3);
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'career-guided-'));for(const d of ['config','modes','data','interview-prep'])fs.mkdirSync(path.join(root,d));fs.writeFileSync(path.join(root,'cv.md'),'# Fictional Candidate\nLed 5 engineers.');fs.writeFileSync(path.join(root,'config/profile.yml'),'target_roles:\n  primary: [Engineer]\n');fs.writeFileSync(path.join(root,'modes/_profile.md'),'# Candidate targeting');fs.writeFileSync(path.join(root,'data/applications.md'),'# Tracker');fs.writeFileSync(path.join(root,'data/pipeline.md'),'- [ ] https://example.com/job | Example | Engineer | Remote\n');fs.writeFileSync(path.join(root,'interview-prep/retracted-claims.md'),'Do not claim ownership of the entire company platform.');return {root,code,candidate:'brad'};}
test('guided context requires full JD, exact operation, candidate-local job and fixed procedure',()=>{const c=fixture();try{assert.throws(()=>guidedContext(c,{kind:'evaluate',jd:'summary'},'chat'),/full job/);assert.throws(()=>guidedContext(c,{kind:'application',jd},'cv'),/does not match/);assert.throws(()=>guidedContext(c,{kind:'evaluate',jd,jobUrl:'https://other.test/job'},'chat'),/unavailable/);assert.throws(()=>guidedContext(c,{kind:'interview',jd,stage:'../../secret'},'chat'),/Choose/);const w=guidedContext(c,{kind:'interview',stage:'practice',jd,jobUrl:'https://example.com/job'},'chat');assert.equal(w.job.company,'Example');assert.match(w.instructions['interview/practice.md'],/Practice/);assert.match(w.references[0].text,/Do not claim/);assert.match(guidedPrompt(w),/No general browser\/search\/shell/);}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('guided review saves verbatim JD, becomes discoverable, is immutable and recovers a dead worker exactly once',()=>{const c=fixture();try{const d=newConversation(c),key=randomUUID(),context=buildAssistantContext(c);context.workflow=guidedContext(c,{kind:'evaluate',jd},'chat');const input={context};d.run={id:key,status:'saving',mode:'chat',workflow:'evaluate',pid:99999999,startedAt:'2020-01-01T00:00:00Z',partial:'Review'};persistConversation(c,d);const result=saveGuidedReview(c,{id:key,conversationId:d.id},input,'Fit needs review.');const bytes=fs.readFileSync(path.join(c.root,result.path),'utf8');assert.ok(bytes.endsWith(jd+'\n'));assert.ok(hostedDocuments(c).documents.some(x=>x.path===result.path));assert.equal(assistantState(c,d.id,{}).conversation.run.status,'completed');assert.equal(assistantState(c,d.id,{}).conversation.messages.length,1);assert.equal(saveGuidedReview(c,{id:key,conversationId:d.id},input,'Fit needs review.').path,result.path);assert.throws(()=>saveGuidedReview(c,{id:key,conversationId:d.id},input,'Different reply'),/without overwriting/);assert.equal(fs.readFileSync(path.join(c.root,'cv.md'),'utf8'),'# Fictional Candidate\nLed 5 engineers.');}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
test('guided paths reject symlink escape before creating review files',()=>{const c=fixture(),outside=fs.mkdtempSync(path.join(os.tmpdir(),'guided-outside-'));try{const d=newConversation(c);fs.symlinkSync(outside,path.join(c.root,'reports'));assert.throws(()=>saveGuidedReview(c,{id:randomUUID(),conversationId:d.id},{context:{workflow:{kind:'evaluate',jd}}},'Review'),/leaves/);assert.deepEqual(fs.readdirSync(outside),[]);}finally{fs.rmSync(c.root,{recursive:true,force:true});fs.rmSync(outside,{recursive:true,force:true});}});
test('guided interview runner saves coaching but rejects proposed CV writes; application retains numeric guard',async()=>{const c=fixture();try{for(const action of [false,true]){const d=newConversation(c),key=randomUUID(),context=buildAssistantContext(c);context.workflow=guidedContext(c,{kind:'interview',stage:'plan',jd},'chat');d.messages=[{role:'user',content:'Prepare my interview.'}];d.run={id:key,status:'queued',mode:'chat',workflow:'interview',partial:''};persistConversation(c,d);const input={context,mode:'chat',messages:d.messages};fs.writeFileSync(path.join(c.root,'.hosted/assistant',d.id,'input-'+key+'.json'),JSON.stringify(input));const reply='Prep plan.'+(action?'\n<career-action>{"type":"cv","content":"Changed"}</career-action>':'');await executeAssistant(c,d.id,key,{env:{CAREER_OPS_AI_URL:'http://127.0.0.1:18791/v1/chat/completions',CAREER_OPS_AI_TOKEN:'fictional'},fetchImpl:async()=>new Response('data: '+JSON.stringify({choices:[{delta:{content:reply}}]})+'\n\ndata: [DONE]\n\n')});assert.equal(readConversation(c,d.id).run.status,action?'failed':'completed');}
const d=newConversation(c),context=buildAssistantContext(c);context.workflow=guidedContext(c,{kind:'application',jd},'draft');assert.throws(()=>applyAssistantAction(c,{id:randomUUID(),conversationId:d.id},{mode:'draft',context,messages:[{role:'user',content:'Prepare packet'}]},{type:'draft',content:'Led 999 engineers.'}),/unsupported number/);
}finally{fs.rmSync(c.root,{recursive:true,force:true});}});
