import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {repairRoot,repairDocument} from '../deploy/review-search-sources.mjs';
test('source review preserves filters, disabled sources and unrelated entries; exact edits and repeatability',()=>{
 const p={title_filter:{positive:['fictional']},tracked_companies:[{name:'HubSpot',careers_url:'https://job-boards.greenhouse.io/hubspot',api:'https://boards-api.greenhouse.io/v1/boards/hubspot/jobs?content=true'},{name:'Weights & Biases',careers_url:'https://coreweave.com/careers/weights-biases'},{name:'Hightouch',enabled:false,careers_url:'https://job-boards.greenhouse.io/hightouch'},{name:'Unrelated',careers_url:'https://example.com'}]};
 const filters=structuredClone(p.title_filter),unrelated=structuredClone(p.tracked_companies.slice(2));
 assert.deepEqual(repairDocument(p).changed,['HubSpot','Weights & Biases']);assert.deepEqual(p.title_filter,filters);assert.deepEqual(p.tracked_companies.slice(2),unrelated);assert.equal(p.tracked_companies[0].api,undefined);assert.match(p.tracked_companies[1].api,/weights_and_biases/);assert.deepEqual(repairDocument(p).changed,[]);
});
test('unexpected source edits are skipped, never overridden',()=>{const p={job_boards:[{name:'HubSpot',careers_url:'https://example.com'}]};assert.deepEqual(repairDocument(p).skipped,['HubSpot']);assert.equal(p.job_boards[0].careers_url,'https://example.com');});

test('authoritative repair uses a private previous-version checkpoint, preserves targeting and dry run does not write',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'source-review-')),code=path.resolve(import.meta.dirname,'../..');try{const file=path.join(root,'portals.yml'),before=JSON.stringify({title_filter:{positive:['fictional']},tracked_companies:[{name:'Hightouch',careers_url:'https://job-boards.greenhouse.io/hightouch',api:'https://boards-api.greenhouse.io/v1/boards/hightouch/jobs'}]});fs.writeFileSync(file,before);assert.deepEqual((await repairRoot(root,code,true)).changed,['Hightouch']);assert.equal(fs.readFileSync(file,'utf8'),before);await repairRoot(root,code);const history=path.join(root,'.hosted/filter-history'),files=fs.readdirSync(history);assert.equal(files.length,1);const backup=path.join(history,files[0]);assert.equal(fs.statSync(backup).mode&0o777,0o600);assert.equal(JSON.parse(fs.readFileSync(backup,'utf8')).before,before);assert.match(fs.readFileSync(file,'utf8'),/fictional/);assert.deepEqual((await repairRoot(root,code)).changed,[]);assert.equal(fs.readdirSync(history).length,1);}finally{fs.rmSync(root,{recursive:true,force:true});}});
