import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';
import {hostedDocuments} from './documents.mjs';import {readSources,digest,StoreError,lock} from './store.mjs';import {safeFile,draftEvidence} from './evaluation-records.mjs';
export function selectExportText(text,section){if(section==='full')return text;if(section!=='resume')throw new StoreError('Choose full document or resume only.');const lines=text.split('\n'),starts=[];for(let i=0;i<lines.length;i++)if(/^#{1,3}\s+(?:tailored\s+)?(?:resume|cv)(?:\s*[-—:]\s*.*)?\s*$/i.test(lines[i]))starts.push(i);if(starts.length!==1)throw new StoreError('A single Resume or Tailored resume heading is required for resume-only export. Ask the Assistant to format the packet with that heading.');const start=starts[0],level=lines[start].match(/^#+/)[0].length;let end=start+1;while(end<lines.length){const boundary=new RegExp('^#{1,'+level+'}\\s+').test(lines[end]);if(boundary&&lines.slice(start+1,end).some(l=>l.trim()))break;end++;}const chosen=lines.slice(start+1,end).join('\n').trim();if(!chosen)throw new StoreError('Resume section is empty.');return chosen;}
export async function exportReview(c,body){
 const d=hostedDocuments(c,body.id);if(d.extension!=='md'||!(d.path==='cv.md'||d.path.startsWith('output/')))throw new StoreError('Select a current Markdown CV or application document.');if(d.size>200000)throw new StoreError('Document is too large to export.',413);const original=Buffer.from(d.data,'base64').toString('utf8'),text=selectExportText(original,body.section),sources=lock(c.root,()=>readSources(c.root));for(const name of ['article-digest.md'])if(fs.existsSync(safeFile(c.root,name)))sources[name]=fs.readFileSync(safeFile(c.root,name),'utf8');const evidence=draftEvidence(c,d.path),statements=(evidence?.messages||[]).filter(m=>m.role==='user').map(m=>m.content).join('\n');let report='',reportPath='',jd=evidence?.context?.workflow?.jd||'';
 if(body.evaluationId){const e=hostedDocuments(c,body.evaluationId);if(e.extension!=='md'||!e.path.startsWith('reports/')||e.size>200000)throw new StoreError('Select a current evaluation report.');reportPath=e.path;report=Buffer.from(e.data,'base64').toString('utf8');jd=report.split('## Job Description (archived verbatim)')[1]||jd;}
 const keywordsModule=await import(/* webpackIgnore: true */ pathToFileURL(path.join(c.code,'keyword-match.mjs')).href),skillsModule=await import(/* webpackIgnore: true */ pathToFileURL(path.join(c.code,'skill-extract.mjs')).href),titlesModule=await import(/* webpackIgnore: true */ pathToFileURL(path.join(c.code,'cv-title-check.mjs')).href);const extracted=keywordsModule.extractKeywords(report),keywords=extracted.length?extracted:[...skillsModule.extractSkills(jd)],coverage=keywords.length?keywordsModule.analyzeCoverage(keywords,text):null;
 const nums=s=>s.match(/\b\d+(?:[.,]\d+)*%?\b/g)||[],known=new Set(nums(Object.values(sources).join('\n')+'\n'+statements)),unsupportedNumbers=[...new Set(nums(text).filter(n=>!known.has(n)))];const primary=titlesModule.parseCvExperience(sources['cv.md']),tailored=titlesModule.parseCvExperience(text),titles=titlesModule.checkTitles(primary,tailored);
 const warnings=['These checks do not verify achievements, authorship, eligibility or every ATS parser. Review every claim.','Numeric matches establish only that a number appears in a source, not that it supports the same claim.'];if(body.section==='full'&&d.path!=='cv.md')warnings.push('Full packet export includes all selected text. Job facts, commentary and answers can affect keyword/number counts; use Resume only for a resume check.');if(!coverage)warnings.push('Keyword check unavailable: no usable job keywords. Select an evaluation with the full JD.');else warnings.push('Keyword coverage is diagnostic; never add an unsupported skill merely to improve this percentage.');if(!primary.length||!tailored.length)warnings.push('Title check unavailable or incomplete: use an Experience section with ### Company, **Title**, and dates on the next line.');if(titles.unmatchedTailored.length||titles.ambiguous.length)warnings.push('Some employment titles could not be paired uniquely by company and dates.');if(unsupportedNumbers.length)warnings.push('Numbers missing from current primary files and the original direct statements require review.');if(titles.mismatches.length)warnings.push('Employment titles differ from the master CV.');
 const fingerprint=digest(JSON.stringify({format:'career-pdf-v1',original,text,sources,statements,report,jd,section:body.section}));return {id:body.id,path:d.path,section:body.section,fingerprint,text,binding:{originalHash:digest(original),primaryHash:digest(JSON.stringify(sources)),statementsHash:digest(statements),evidenceHash:digest(JSON.stringify(evidence)),reportPath,reportHash:digest(report)},checks:{coverage,keywordSource:extracted.length?'Evaluation keyword block':'Recognized technology names in archived JD',unsupportedNumbers,titles,titleCoverage:{primary:primary.length,exported:tailored.length,compared:titles.matched.length+titles.mismatches.length},warnings},evaluations:[]};
}
const escape=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function plain(s){return s.replace(/!\[([^\]]*)\]\([^)]*\)/g,'[Image omitted: $1]').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1 ($2)').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/`([^`]+)`/g,'$1');}
export function pdfHtml(text){const blocks=text.replace(/\r/g,'').split('\n\n').map(block=>{const h=block.match(/^(#{1,6})\s+([^\n]+)$/);if(h)return '<h'+h[1].length+'>'+escape(plain(h[2]))+'</h'+h[1].length+'>';return '<p>'+escape(plain(block)).replace(/\n/g,'<br>')+'</p>';}).join('\n');return '<!doctype html><html><head><meta charset="utf-8"><style>@page{size:Letter}body{font-family:Arial,sans-serif;font-size:10.5pt;line-height:1.45;color:#17202a}h1{font-size:22pt}h2{font-size:14pt;border-bottom:1px solid #ddd;padding-bottom:4pt}h3{font-size:12pt}h1,h2,h3,h4,h5,h6{break-after:avoid}p{orphans:3;widows:3;overflow-wrap:anywhere}h1,h2,h3,p{margin:0 0 10pt}pre{white-space:pre-wrap}</style></head><body>'+blocks+'</body></html>';}
export async function renderPdf(c,text){const require=createRequire(path.join(c.code,'web/package.json')),{chromium}=require('playwright-core');let browser;try{browser=await chromium.launch({...(process.platform==='linux'?{executablePath:'/usr/bin/google-chrome'}:{}),headless:true,args:['--no-sandbox']});const context=await browser.newContext({javaScriptEnabled:false});await context.route('**/*',r=>r.abort());const page=await context.newPage();await page.setContent(pdfHtml(text),{waitUntil:'load',timeout:15000});return await page.pdf({format:'Letter',printBackground:false,margin:{top:'0.6in',bottom:'0.65in',left:'0.65in',right:'0.65in'},displayHeaderFooter:true,headerTemplate:'<span></span>',footerTemplate:'<div style="font-family:Arial;font-size:8px;width:100%;text-align:center;color:#666"><span class="pageNumber"></span> / <span class="totalPages"></span></div>',timeout:20000});}finally{await browser?.close();}}
export async function saveExport(c,body,{renderer=renderPdf}={}){if(body.acknowledged!==true)throw new StoreError('Review the checks and acknowledge human review before exporting.');const review=await exportReview(c,body);if(body.fingerprint!==review.fingerprint)throw new StoreError('Document or evidence changed. Refresh the quality review before exporting.',409);const pdf=await renderer(c,review.text);if(!Buffer.isBuffer(pdf)||!pdf.subarray(0,5).equals(Buffer.from('%PDF-'))||pdf.length>10000000)throw new StoreError('PDF rendering failed; no export was saved.',503);
 return lock(c.root,()=>{const sources=readSources(c.root);if(fs.existsSync(safeFile(c.root,'article-digest.md')))sources['article-digest.md']=fs.readFileSync(safeFile(c.root,'article-digest.md'),'utf8');const evidence=draftEvidence(c,review.path);const statements=(evidence?.messages||[]).filter(m=>m.role==='user').map(m=>m.content).join('\n');const report=review.binding.reportPath?fs.readFileSync(safeFile(c.root,review.binding.reportPath),'utf8'):'';if(digest(fs.readFileSync(safeFile(c.root,review.path)))!==review.binding.originalHash||digest(JSON.stringify(sources))!==review.binding.primaryHash||digest(statements)!==review.binding.statementsHash||digest(JSON.stringify(evidence))!==review.binding.evidenceHash||digest(report)!==review.binding.reportHash)throw new StoreError('Source or evidence changed during rendering. Refresh the checks.',409);return saveFiles(c,review,pdf);});
}
function saveFiles(c,review,pdf){const stem=path.basename(review.path,'.md').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,70)+'-'+review.section+'-'+review.fingerprint.slice(0,16),relative='output/pdf/'+stem+'.pdf',notes='output/pdf/'+stem+'-checks.md';const dir=safeFile(c.root,'output/pdf');fs.mkdirSync(dir,{recursive:true,mode:0o700});const file=safeFile(c.root,relative),note=safeFile(c.root,notes),checkText='# PDF export quality review\n\nSource: '+review.path+'\nSection: '+review.section+'\nFingerprint: '+review.fingerprint+'\nHuman review acknowledged; this does not verify facts or submit an application.\n\n```json\n'+JSON.stringify(review.checks,null,2)+'\n```\n';
 const receipt=safeFile(c.root,'.hosted/pdf-exports/'+review.fingerprint+'.json');fs.mkdirSync(path.dirname(receipt),{recursive:true,mode:0o700});let saved;if(fs.existsSync(receipt)){saved=JSON.parse(fs.readFileSync(receipt,'utf8'));if(saved.path!==relative||saved.checksPath!==notes)throw new StoreError('Export receipt differs; retained.',409);}else{if(fs.existsSync(file)||fs.existsSync(note))throw new StoreError('Untracked export already exists. Review before retrying.',409);const staged=safeFile(c.root,'.hosted/pdf-exports/'+review.fingerprint+'.pdf');if(!fs.existsSync(staged)){const tmp=staged+'.tmp';fs.writeFileSync(tmp,pdf,{mode:0o600,flag:'wx'});fs.renameSync(tmp,staged);}const originalPdf=fs.readFileSync(staged);if(!originalPdf.subarray(0,5).equals(Buffer.from('%PDF-')))throw new StoreError('Staged PDF is invalid.',409);saved={path:relative,checksPath:notes,pdfHash:digest(originalPdf),checksHash:digest(checkText)};fs.writeFileSync(receipt,JSON.stringify(saved),{mode:0o600,flag:'wx'});}
 for(const [target,bytes,expected]of [[file,fs.existsSync(file)?pdf:fs.readFileSync(safeFile(c.root,'.hosted/pdf-exports/'+review.fingerprint+'.pdf')),saved.pdfHash],[note,Buffer.from(checkText),saved.checksHash]]){if(fs.existsSync(target)){if(digest(fs.readFileSync(target))!==expected)throw new StoreError('An existing export differs; retained.',409);continue;}if(digest(bytes)!==expected)throw new StoreError('Interrupted PDF export requires the original render; refresh and use a new export version.',409);const tmp=target+'.'+randomUUID()+'.tmp';try{fs.writeFileSync(tmp,bytes,{mode:0o600,flag:'wx'});fs.renameSync(tmp,target);}finally{fs.rmSync(tmp,{force:true});}}
 return {ok:true,path:relative,checksPath:notes,documentId:digest(c.candidate+':current:'+relative)};
}
