import fs from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {lock,StoreError,readState,savedAssistantOperation,digest} from './store.mjs';
import {atomicJSON,readJob} from './search.mjs';
import {projectKnowledge,workspaceSnapshot} from './project-context.mjs';
import {hostedDocuments} from './documents.mjs';
import {guidedContext,guidedPath} from './guided-workflows.mjs';
const idRE=/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/;
export const MODES=['chat','draft','cv','profile','search','pipeline'];
export function assistantDir(c,id){if(!idRE.test(id||''))throw new StoreError('Invalid conversation identifier.');const dir=path.join(c.root,'.hosted/assistant',id),base=fs.realpathSync(c.root);for(const folder of [path.join(c.root,'.hosted'),path.join(c.root,'.hosted/assistant'),dir])if(fs.existsSync(folder)&&(fs.lstatSync(folder).isSymbolicLink()||!fs.realpathSync(folder).startsWith(base+path.sep)))throw new StoreError('Conversation leaves its workspace.',403);return dir;}
export function readConversation(c,id){const file=path.join(assistantDir(c,id),'conversation.json');if(!fs.existsSync(file))throw new StoreError('Conversation not found in this workspace.',404);if(fs.lstatSync(file).isSymbolicLink()||!fs.realpathSync(file).startsWith(fs.realpathSync(c.root)+path.sep))throw new StoreError('Conversation leaves its workspace.',403);const data=JSON.parse(fs.readFileSync(file,'utf8'));if(data.candidate!==c.candidate)throw new StoreError('Conversation belongs to another workspace.',403);return data;}
export function persistConversation(c,data){atomicJSON(path.join(assistantDir(c,data.id),'conversation.json'),data);}
export function assistantSettings(env=process.env){const enabled=env.CAREER_OPS_ASSISTANT_ENABLED==='1';if(!enabled)return {enabled:false,provider:'Not connected',paidFallback:false};const url=new URL(env.CAREER_OPS_AI_URL||'');if(url.protocol!=='http:'||url.hostname!=='127.0.0.1'||url.pathname!=='/v1/chat/completions'||url.username||url.password||url.search||url.hash)throw new StoreError('Career assistant transport is not private.',503);if(!env.CAREER_OPS_AI_TOKEN)throw new StoreError('Career assistant is not configured.',503);return {enabled:true,provider:'OpenClaw · OpenAI first, OpenRouter fallback',paidFallback:true};}
export function assistantState(c,id,env=process.env){const settings=assistantSettings(env);if(id)recoverAssistant(c,id);return lock(c.root,()=>{const root=path.join(c.root,'.hosted/assistant');const list=fs.existsSync(root)?fs.readdirSync(root).filter(x=>idRE.test(x)).map(x=>{try{const d=readConversation(c,x);return {id:d.id,title:d.title,updatedAt:d.updatedAt,status:d.run?.status||'idle'};}catch{return null;}}).filter(Boolean).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)):[];return {settings,conversations:list,conversation:id?readConversation(c,id):null};});}
export function newConversation(c){return lock(c.root,()=>{const at=new Date().toISOString(),d={id:randomUUID(),candidate:c.candidate,title:'New conversation',createdAt:at,updatedAt:at,messages:[],run:null};persistConversation(c,d);return d;});}
export function buildAssistantContext(c,documentIds=[]){const state=readState(c);const sources={...state.contents};for(const file of ['article-digest.md','modes/_custom.md','voice-dna.md']){const full=path.join(c.root,file);if(fs.existsSync(full)){if(!fs.realpathSync(full).startsWith(fs.realpathSync(c.root)+path.sep))throw new StoreError('Source leaves its workspace.',403);sources[file]=fs.readFileSync(full,'utf8');}}if(JSON.stringify(sources).length>250000)throw new StoreError('Primary sources exceed assistant context limit.',413);if(!Array.isArray(documentIds)||documentIds.length>3)throw new StoreError('Choose up to three job documents.');const references=[];const catalog=hostedDocuments(c);for(const file of Object.keys(sources)){if(!catalog.documents.some(d=>d.source==='current'&&d.path===file))throw new StoreError('A primary source is restricted or unavailable.',409);}const story=catalog.documents.find(d=>d.source==='current'&&d.path==='interview-prep/story-bank.md');if(story){const raw=hostedDocuments(c,story.id);if(raw.size<=60000)references.push({path:story.path,text:Buffer.from(raw.data,'base64').toString('utf8'),trust:'Derived narrative only; numbers need primary provenance.'});}for(const id of documentIds){const d=catalog.documents.find(d=>d.id===id&&d.source==='current'&&['Job evaluations','Search reports'].includes(d.type));if(!d)throw new StoreError('Selected job document is unavailable.');const raw=hostedDocuments(c,id);if(raw.size>60000)throw new StoreError('Selected job document is too large.');references.push({path:d.path,text:Buffer.from(raw.data,'base64').toString('utf8')});}return {sources,references,revision:state.revision,profile:state.profile,project:projectKnowledge(c),workspace:workspaceSnapshot(c,state)};}
export function sendAssistant(c,input,env=process.env){assistantSettings(env);if(env.CAREER_OPS_ASSISTANT_ENABLED!=='1')throw new StoreError('Assistant is not connected yet.',503);if(!MODES.includes(input.mode)||typeof input.message!=='string'||!input.message.trim()||Buffer.byteLength(input.message)>10000||!idRE.test(input.key||''))throw new StoreError('A message, operation and request identifier are required.');const context=buildAssistantContext(c,input.documentIds||[]);context.workflow=guidedContext(c,input.workflow,input.mode);let selection=null;if(input.mode==='pipeline'){if(!input.selection||typeof input.selection.offerId!=='string')throw new StoreError('Select a saved search match first.');const job=readJob(c,input.selection.searchId),offer=job.offers.find(o=>o.id===input.selection.offerId);if(!offer)throw new StoreError('Selected job is unavailable.');selection={searchId:job.id,offerId:offer.id};context.references.push({path:'selected search match',text:JSON.stringify(offer)});}return lock(c.root,()=>{const d=readConversation(c,input.id);if(d.messages.some(m=>m.key===input.key))return d;if(d.run&&['queued','running','saving'].includes(d.run.status))throw new StoreError('Wait for or cancel the current reply.',409);if(d.messages.length>=80)throw new StoreError('Start a new conversation to keep context manageable.',409);const at=new Date().toISOString();d.messages.push({role:'user',content:input.message,key:input.key,at,mode:input.mode});d.title=d.messages.find(m=>m.role==='user').content.slice(0,80);d.updatedAt=at;d.run={id:input.key,status:'queued',mode:input.mode,workflow:context.workflow?.kind,startedAt:at,partial:'',provider:'Configured: OpenAI first, OpenRouter fallback',paidFallback:true,operationId:Date.now()+'-'+input.key};const dir=assistantDir(c,d.id);atomicJSON(path.join(dir,'input-'+input.key+'.json'),{context,selection,message:input.message,mode:input.mode,messages:d.messages.slice(-30),operationId:d.run.operationId});persistConversation(c,d);const logFd=fs.openSync(path.join(dir,'worker-'+input.key+'.log'),'a',0o600);const child=spawn(process.execPath,[path.join(c.code,'portal/assistant-worker.mjs'),c.candidate,c.root,c.code,d.id,input.key],{cwd:c.code,detached:true,stdio:['ignore',logFd,logFd],env:{PATH:env.PATH||'/usr/bin:/bin',HOME:env.HOME||'',CAREER_OPS_AI_URL:env.CAREER_OPS_AI_URL,CAREER_OPS_AI_TOKEN:env.CAREER_OPS_AI_TOKEN}});fs.closeSync(logFd);child.unref();child.on('error',()=>{try{lock(c.root,()=>{const latest=readConversation(c,d.id);latest.run.status='failed';latest.run.error='Assistant could not start; your message was retained.';persistConversation(c,latest);});}catch{}});d.run.pid=child.pid||null;persistConversation(c,d);return d;});}
export function cancelAssistant(c,id){return lock(c.root,()=>{const d=readConversation(c,id);if(d.run&&['queued','running','saving'].includes(d.run.status)){atomicJSON(path.join(assistantDir(c,id),'cancel-'+d.run.id+'.json'),{at:new Date().toISOString()});d.run.cancelRequested=true;persistConversation(c,d);}return d;});}

export function recoverAssistant(c,id){
 const d=lock(c.root,()=>readConversation(c,id)),r=d.run;if(!r||!['queued','running','saving'].includes(r.status)||Date.now()-Date.parse(r.startedAt)<5000)return;
 let alive=false;if(r.pid){try{process.kill(r.pid,0);alive=true;if(process.platform==='linux'){const args=fs.readFileSync('/proc/'+r.pid+'/cmdline','utf8');alive=args.includes('/portal/assistant-worker.mjs')&&args.split('\0').includes(r.id)&&args.split('\0').includes(id);}}catch{}}else if(Date.now()-Date.parse(r.startedAt)<10000)return;
 if(alive)return;
 let result=null;if(['cv','profile'].includes(r.mode)&&r.operationId&&savedAssistantOperation(c,r.operationId))result={kind:r.mode,recovered:true};
 if(r.workflow&&['evaluate','interview'].includes(r.workflow)){try{const receipt=JSON.parse(fs.readFileSync(path.join(assistantDir(c,id),'operation-'+r.id+'.json'),'utf8'));const expected=guidedPath(r.workflow,r.id),file=path.join(c.root,expected);if(receipt.path===expected&&fs.realpathSync(file).startsWith(fs.realpathSync(c.root)+path.sep)&&digest(fs.readFileSync(file,'utf8'))===receipt.hash)result={kind:r.workflow,path:expected,recovered:true};}catch{}}
 if(r.mode==='draft'){try{const receipt=JSON.parse(fs.readFileSync(path.join(assistantDir(c,id),'operation-'+r.id+'.json'),'utf8'));const expected='output/assistant/'+r.id+'.md';const file=path.join(c.root,expected);if(receipt.path===expected&&fs.realpathSync(file).startsWith(fs.realpathSync(c.root)+path.sep)&&digest(fs.readFileSync(file,'utf8'))===receipt.hash)result={kind:'draft',path:expected,recovered:true};}catch{}}
 return lock(c.root,()=>{const latest=readConversation(c,id);if(latest.run?.id!==r.id||!['queued','running','saving'].includes(latest.run.status))return;if(result){latest.run.status='completed';latest.run.result=result;latest.messages.push({role:'assistant',content:r.partial||'The saved change was recovered after an interrupted connection.',at:new Date().toISOString(),operation:result});latest.run.partial='';}else{latest.run.status='interrupted';latest.run.error='The reply was interrupted. Your message and proposed text are retained; completed saves remain available.';}latest.updatedAt=new Date().toISOString();persistConversation(c,latest);});
}

// Explicit browser save exports an existing reply verbatim; it does not regenerate candidate facts.
export function saveAssistantResponse(c,input){
 if(!Number.isInteger(input.index)||input.index<0)throw new StoreError('Choose a completed assistant response.');
 return lock(c.root,()=>{
  const d=readConversation(c,input.id),m=d.messages[input.index];
  if(!m||m.role!=='assistant'||typeof m.content!=='string'||!m.content.trim()||Buffer.byteLength(m.content)>200000)throw new StoreError('Choose a completed assistant response.');
  const relative='output/assistant/response-'+d.id+'-'+input.index+'.md',file=path.join(c.root,relative),base=fs.realpathSync(c.root);
  for(const folder of [path.join(c.root,'output'),path.join(c.root,'output/assistant')]){
   if(fs.existsSync(folder)&&(fs.lstatSync(folder).isSymbolicLink()||!fs.realpathSync(folder).startsWith(base+path.sep)))throw new StoreError('Response path leaves its workspace.',403);
   if(!fs.existsSync(folder))fs.mkdirSync(folder,{mode:0o700});
  }
  const content='# Saved career assistant response\n\nAI-generated discussion, saved verbatim for review. This is not a verified source of candidate facts.\n\n---\n\n'+m.content+'\n';
  if(fs.existsSync(file)){
   if(fs.lstatSync(file).isSymbolicLink()||!fs.realpathSync(file).startsWith(base+path.sep))throw new StoreError('Response path leaves its workspace.',403);
   if(fs.readFileSync(file,'utf8')!==content)throw new StoreError('The saved document has changed; it was retained without overwriting.',409);
  }else{
   const temp=file+'.'+randomUUID()+'.tmp';
   try{fs.writeFileSync(temp,content,{mode:0o600,flag:'wx'});fs.renameSync(temp,file);}finally{fs.rmSync(temp,{force:true});}
  }
  m.savedResponse={path:relative,documentId:digest(c.candidate+':current:'+relative),at:m.savedResponse?.at||new Date().toISOString(),actor:'shared-login'};
  d.updatedAt=new Date().toISOString();persistConversation(c,d);return d;
 });
}
