import fs from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {spawn,execFileSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import * as yaml from 'js-yaml';
import {lock,readSources,digest,StoreError} from './store.mjs';
import {profileTargetKeywords} from '../profile-keywords.mjs';
import {existingOpportunities} from './search-settings.mjs';
import {titleFit} from '../title-fit.mjs';

export function safeCareerUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
export const LIMITS={milliseconds:600000,offers:250,boards:100,concurrency:2};
export const activeStates=['queued','running'];
const idRE=/^[a-f0-9-]{36}$/;
export function atomicJSON(file,value){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});const tmp=file+'.'+randomUUID()+'.tmp';fs.writeFileSync(tmp,JSON.stringify(value),{mode:0o600});fs.renameSync(tmp,file);}
export function saveReceipt(c,j){atomicJSON(path.join(jobDir(c,j.id),'receipt.json'),j);const dir=path.join(c.root,'data/search-reports');fs.mkdirSync(dir,{recursive:true,mode:0o700});if(!fs.realpathSync(dir).startsWith(fs.realpathSync(c.root)+path.sep))throw new StoreError('Search report path leaves candidate root.',409);const clean=v=>String(v??'').replace(/[\r\n|<>]/g,' ');const text=`# Preliminary search — ${c.candidate}\n\nStarted: ${j.startedAt}\nStatus: ${j.status}\nTargeting revision: ${j.revision}\n${j.reason||''}\n\n${j.counts.found} postings found; ${j.counts.filtered} filtered; ${j.counts.duplicates} already known.\n\nTitle fit is preliminary. Salary, benefits, location, travel and eligibility require review. No application was sent.\n\n## Source coverage\n\n`+j.sources.map(s=>`- ${clean(s.company)}: ${s.status}; retrieved ${clean(s.retrievedAt||'not fetched')}; ${clean(s.error||'')}\n`).join('')+'\n## Saved matches\n\n'+j.offers.map((o,i)=>`${i+1}. ${clean(o.company)} — ${clean(o.title)}\n   ${clean(o.location)}; title fit: ${o.fit?.band||'unknown'}; ${j.selected.includes(o.id)?'added to pipeline':'not selected'}\n   ${o.url}\n   Advertised compensation: ${o.salary?clean(JSON.stringify(o.salary)):'unknown'}\n   Needs verification: ${o.unknown.join(', ')}\n`).join('\n');const file=path.join(dir,j.id+'.md'),tmp=file+'.tmp';fs.writeFileSync(tmp,text,{mode:0o600});fs.renameSync(tmp,file);}
export function jobDir(c,id){if(!idRE.test(String(id)))throw new StoreError('Invalid search identifier.');return path.join(c.root,'.hosted/search',id);}
export function readJob(c,id){const j=JSON.parse(fs.readFileSync(path.join(jobDir(c,id),'receipt.json'),'utf8'));if(j.candidate!==c.candidate)throw new StoreError('Search belongs to another workspace.',403);return j;}
export function cleanEnvironment(root,code){return {PATH:process.env.PATH||'/usr/bin:/bin',LANG:'en_US.UTF-8',TZ:process.env.TZ||'America/Detroit',CAREER_OPS_ROOT:root,CAREER_OPS_CODE_ROOT:code,CAREER_OPS_HOSTED_SCAN:'1',CAREER_OPS_SCAN_PREVIEW_RECEIPT:'1'};}
function readWithin(root,name,optional=false){const file=path.join(root,name);try{if(!fs.realpathSync(file).startsWith(fs.realpathSync(root)+path.sep))throw new StoreError('Candidate source leaves its workspace.',409);return fs.readFileSync(file,'utf8');}catch(e){if(optional&&e.code==='ENOENT')return '';throw e;}}
function mapping(text,label){let p;try{p=yaml.load(text);}catch{throw new StoreError(label+' is malformed; repair it before searching.',409);}if(!p||typeof p!=='object'||Array.isArray(p))throw new StoreError(label+' must be a mapping.',409);return p;}

// Reconstruct entries rather than forwarding custom parser commands, headers or URLs.
export function publicBoard(entry){
 if(!entry||typeof entry!=='object'||entry.enabled===false)return null;
 const name=typeof entry.name==='string'?entry.name.slice(0,150):'';
 if(!name)throw new Error('Board name is missing');
 const u=new URL(entry.api||entry.careers_url||'');if(u.protocol!=='https:'||u.username||u.password||u.port)throw new Error('Public HTTPS board required');
 let provider,slug,api,careers_url;
 if(['boards-api.greenhouse.io','boards.greenhouse.io','boards.eu.greenhouse.io','job-boards.greenhouse.io','job-boards.eu.greenhouse.io'].includes(u.hostname)){
  provider='greenhouse';slug=u.hostname==='boards-api.greenhouse.io'?u.pathname.match(/^\/v1\/boards\/([^/]+)\/jobs\/?$/)?.[1]:u.pathname.split('/').filter(Boolean)[0];if(slug==='embed')slug=u.searchParams.get('for');api=`https://boards-api.greenhouse.io/v1/boards/${slug}/jobs?content=true`;careers_url=`https://job-boards.greenhouse.io/${slug}`;
 }else if(['api.ashbyhq.com','jobs.ashbyhq.com'].includes(u.hostname)){
  provider='ashby';slug=u.hostname==='api.ashbyhq.com'?u.pathname.match(/^\/posting-api\/job-board\/([^/]+)\/?$/)?.[1]:u.pathname.split('/').filter(Boolean)[0];api=`https://api.ashbyhq.com/posting-api/job-board/${slug}?includeCompensation=true`;careers_url=`https://jobs.ashbyhq.com/${slug}`;
 }else if(['api.lever.co','api.eu.lever.co','jobs.lever.co','jobs.eu.lever.co'].includes(u.hostname)){
  provider='lever';slug=u.hostname.startsWith('api.')?u.pathname.match(/^\/v0\/postings\/([^/]+)\/?$/)?.[1]:u.pathname.split('/').filter(Boolean)[0];const region=u.hostname.includes('.eu.')?'eu.':'';api=`https://api.${region}lever.co/v0/postings/${slug}`;careers_url=`https://jobs.${region}lever.co/${slug}`;
 }else throw new Error('Not a supported Greenhouse, Ashby or Lever board');
 if(!/^[a-zA-Z0-9_-]{1,150}$/.test(slug||''))throw new Error('Invalid public board identifier');
 return {name,provider,api,careers_url,enabled:true};
}
export function snapshot(c){
 const sources=readSources(c.root),profile=mapping(sources['config/profile.yml'],'Profile'),portals=mapping(readWithin(c.root,'portals.yml'),'Portals');
 const targets=profileTargetKeywords(profile).map(s=>s.trim()).filter(Boolean);if(!targets.length)throw new StoreError('Add target roles to your profile before searching.',409);
 const boards=[],unsupported=[];
 for(const e of [...(Array.isArray(portals.tracked_companies)?portals.tracked_companies:[]),...(Array.isArray(portals.job_boards)?portals.job_boards:[])]){if(e?.enabled===false)continue;try{const b=publicBoard(e);if(b&&!boards.some(x=>x.api===b.api))boards.push(b);}catch(error){unsupported.push({company:typeof e?.name==='string'?e.name:'Unnamed board',status:'unsupported',error:error.message,url:safeCareerUrl(e?.careers_url)});}}
 if(!boards.length)throw new StoreError('No supported public boards configured. Add Greenhouse, Ashby or Lever boards to portals.yml.',409);
 const filters={};for(const key of ['title_filter','location_filter','skip_tiers','max_posting_age_days','salary_filter','trust_filter','content_filter','country_eligibility_filter','visa_filter','dedup'])if(portals[key]!==undefined)filters[key]=portals[key];
 if(!filters.title_filter?.positive?.length)filters.title_filter={...filters.title_filter,positive:targets};
 return {sources,profile,targets,filters,boards:boards.slice(0,LIMITS.boards),unsupported,boardCap:boards.length>LIMITS.boards,revision:digest(JSON.stringify(sources)+readWithin(c.root,'portals.yml')),dedup:Object.fromEntries(['data/applications.md','data/pipeline.md','data/scan-history.tsv','data/blacklist.md','data/status-log.tsv'].map(f=>[f,readWithin(c.root,f,true)]))};
}
export function rankOffers(offers,targets){return offers.map(o=>{let u;try{u=new URL(o.url);}catch{return null;}if(u.protocol!=='https:'||u.username||u.password)return null;return {id:digest(o.url).slice(0,24),url:u.href,company:String(o.company||'').slice(0,200),title:String(o.title||'').slice(0,300),location:String(o.location||'Unknown').slice(0,500),source:String(o.source||''),retrievedAt:o.retrievedAt||null,postedAt:o.postedAt||null,salary:o.salary||null,fit:titleFit(o.title,targets),unknown:['Benefits','Remote location eligibility','Travel requirements','Work authorization eligibility',...(!o.salary?['Compensation']:[]) ]};}).filter(Boolean).sort((a,b)=>(b.fit?.score||0)-(a.fit?.score||0)||a.title.localeCompare(b.title));}
function liveRunner(c,j){if(!j.pid)return false;try{if(process.platform==='linux'){const cmd=fs.readFileSync(`/proc/${j.pid}/cmdline`,'utf8');return cmd.includes(path.join(c.code,'portal/search-worker.mjs'))&&cmd.split('\0').includes(j.id)&&fs.readFileSync(`/proc/${j.pid}/stat`,'utf8').split(') ')[1].split(' ')[0]!=='Z';}const command=execFileSync('/bin/ps',['-p',String(j.pid),'-o','command='],{encoding:'utf8',stdio:['ignore','pipe','ignore']});return command.includes(path.join(c.code,'portal/search-worker.mjs'))&&command.includes(j.id);}catch{return false;}}
export function searchState(c,id){return lock(c.root,()=>{const dir=path.join(c.root,'.hosted/search');fs.mkdirSync(dir,{recursive:true,mode:0o700});const jobs=fs.readdirSync(dir).filter(x=>idRE.test(x)).map(x=>readJob(c,x));for(const j of jobs)if(activeStates.includes(j.status)&&!liveRunner(c,j)&&Date.now()-Date.parse(j.startedAt)>5000){j.status='interrupted';j.finishedAt=new Date().toISOString();j.reason='The search service stopped. Start a new search to refresh coverage.';saveReceipt(c,j);}jobs.sort((a,b)=>b.startedAt.localeCompare(a.startedAt));const selected=id?jobs.find(j=>j.id===id):jobs[0];if(id&&!selected)throw new StoreError('Search not found.',404);return {candidate:c.candidate,limits:LIMITS,existing:existingOpportunities(c),jobs:jobs.map(({offers,...j})=>({...j,offerCount:offers.length})),run:selected?{...selected,outdated:selected.revision!==digest(JSON.stringify(readSources(c.root))+readWithin(c.root,'portals.yml'))&&(selected.revision!==digest(JSON.stringify(readSources(c.root)))||fs.existsSync(path.join(c.root,'.hosted/filter-history')))}:null};});}
export function startSearch(c,input){if(!idRE.test(String(input.key)))throw new StoreError('A valid request identifier is required.');return lock(c.root,()=>{const dir=path.join(c.root,'.hosted/search');fs.mkdirSync(dir,{recursive:true,mode:0o700});for(const id of fs.readdirSync(dir).filter(x=>idRE.test(x))){const j=readJob(c,id);if(j.key===input.key)return {id:j.id};if(activeStates.includes(j.status)&&(liveRunner(c,j)||Date.now()-Date.parse(j.startedAt)<5000))throw new StoreError('A search is already running in this workspace.',409);}
 const s=snapshot(c),id=randomUUID(),d=jobDir(c,id);fs.mkdirSync(d,{mode:0o700});const job={id,key:input.key,candidate:c.candidate,revision:s.revision,startedAt:new Date().toISOString(),status:'queued',offers:[],sources:s.unsupported,counts:{found:0,filtered:0,duplicates:0},selected:[],limits:LIMITS};atomicJSON(path.join(d,'input.json'),s);atomicJSON(path.join(d,'receipt.json'),job);
 const child=spawn(process.execPath,[path.join(c.code,'portal/search-worker.mjs'),c.root,c.candidate,id],{cwd:d,env:cleanEnvironment(c.root,c.code),stdio:'ignore'});if(!child.pid){job.status='failed';job.reason='Search worker could not start.';}else job.pid=child.pid;child.on('error',()=>{});child.unref();atomicJSON(path.join(d,'receipt.json'),job);return {id};});}
export function cancelSearch(c,id){return lock(c.root,()=>{const j=readJob(c,id);if(activeStates.includes(j.status))atomicJSON(path.join(jobDir(c,id),'cancel.json'),{at:new Date().toISOString()});return {id};});}
export function publishSelected(c,input){return lock(c.root,()=>{const j=readJob(c,input.id);if(activeStates.includes(j.status))throw new StoreError('Wait for the search to finish before adding jobs.',409);if(!Array.isArray(input.ids)||!input.ids.length||input.ids.length>250||input.ids.some(id=>typeof id!=='string'||!j.offers.some(o=>o.id===id)))throw new StoreError('Select saved results from this workspace.');
 const d=jobDir(c,j.id),pf=path.join(d,'publication.json'),previous=fs.existsSync(pf)?JSON.parse(fs.readFileSync(pf,'utf8')):null;const ids=[...new Set([...input.ids,...(previous?.status==='pending'?previous.ids:[])])];for(const other of fs.readdirSync(path.join(c.root,'.hosted/search')).filter(x=>idRE.test(x)&&x!==j.id)){const file=path.join(jobDir(c,other),'publication.json');if(fs.existsSync(file)&&JSON.parse(fs.readFileSync(file,'utf8')).status==='pending')throw new StoreError('Retry the unfinished selection in its saved search before adding other jobs.',409);}const offers=j.offers.filter(o=>ids.includes(o.id)&&(!j.selected.includes(o.id)||(previous?.status==='pending'&&previous.ids.includes(o.id))));if(!offers.length)return {added:0};
 const publication={ids:offers.map(o=>o.id),status:'pending',at:new Date().toISOString(),before:previous?.status==='pending'?previous.before:Object.fromEntries(['data/pipeline.md','data/scan-history.tsv'].map(f=>[f,readWithin(c.root,f,true)]))};atomicJSON(path.join(d,'publication.json'),publication);
 const script=`import fs from 'node:fs';import {appendToPipeline,appendToScanHistory,normalizeUrlForDedup,collectSeenUrls,unrecordedOffers,loadBlacklist,findBlacklistEntry} from ${JSON.stringify(pathToFileURL(path.join(c.code,'scan.mjs')).href)};import {localToday} from ${JSON.stringify(pathToFileURL(path.join(c.code,'lib/local-today.mjs')).href)};let raw='';for await(const chunk of process.stdin)raw+=chunk;const offers=JSON.parse(raw);const blacklist=loadBlacklist();const pipeline=${JSON.stringify(path.join(c.root,'data/pipeline.md'))};const history=${JSON.stringify(path.join(c.root,'data/scan-history.tsv'))};const text=fs.existsSync(pipeline)?fs.readFileSync(pipeline,'utf8'):'';const tracker=${JSON.stringify(path.join(c.root,'data/applications.md'))};const known=collectSeenUrls({pipelineText:text,applicationsText:fs.existsSync(tracker)?fs.readFileSync(tracker,'utf8'):''}).seen;const fresh=offers.filter(o=>!known.has(normalizeUrlForDedup(o.url)));if(fresh.some(o=>findBlacklistEntry(blacklist,o.company,o.url)))throw new Error('A selected company is now blacklisted. Refresh your selection.');await appendToPipeline(fresh);const pending=unrecordedOffers(offers,'added',fs.existsSync(history)?fs.readFileSync(history,'utf8'):'');if(pending.length)await appendToScanHistory(pending,localToday(),'added');process.stdout.write(JSON.stringify({added:fresh.length}));`;
 let result;try{result=JSON.parse(execFileSync(process.execPath,['--input-type=module','-e',script],{cwd:d,env:cleanEnvironment(c.root,c.code),input:JSON.stringify(offers),timeout:20000,maxBuffer:200000,encoding:'utf8',stdio:['pipe','pipe','pipe']}));}catch(e){if(String(e.stderr||'').includes('selected company is now blacklisted')){if(Object.entries(publication.before||{}).every(([f,text])=>readWithin(c.root,f,true)===text))atomicJSON(path.join(d,'publication.json'),{...publication,status:'rejected'});throw new StoreError('A selected company is now blacklisted. Refresh your selection.',409);}throw new StoreError('Adding jobs could not be confirmed. Results are retained; retry reconciles saved jobs.',503);}
 j.selected=[...new Set([...j.selected,...offers.map(o=>o.id)])];saveReceipt(c,j);atomicJSON(path.join(d,'publication.json'),{...publication,status:'completed',completedAt:new Date().toISOString()});return result;});}
