"use client";
import {useEffect,useState} from 'react';
import {HostedSearchFilters} from './hosted-search-filters';
type Offer={id:string;title:string;company:string;url:string;location:string;source:string;retrievedAt?:string;salary:{min?:number;max?:number;currency?:string}|null;fit:{band:string}|null;unknown:string[]};
type Run={id:string;status:string;reason?:string;startedAt:string;outdated:boolean;offers:Offer[];selected:string[];counts:{found:number;filtered:number;duplicates:number};sources:{company:string;status:string;found?:number;matches?:number;error?:string;url?:string;filters?:Record<string,number>}[]};
type State={existing:{url:string;title:string;company:string;location:string;status:string;lastSeen:string|null}[];run:Run|null;jobs:{id:string;status:string;startedAt:string;offerCount:number}[]};
const endpoint=(process.env.NEXT_PUBLIC_HOSTED_BASE||'')+'/api/hosted/search';
export function HostedSearch(){
 const [action,setAction]=useState(''),[refreshing,setRefreshing]=useState(false);
 const [showFilters,setShowFilters]=useState(false),[showExisting,setShowExisting]=useState(false),[query,setQuery]=useState('');
 const [data,setData]=useState<State|null>(null),[id,setId]=useState(''),[message,setMessage]=useState(''),[loadError,setLoadError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([]);
 async function load(job=id,manual=false){if(manual)setRefreshing(true);try{const r=await fetch(endpoint+(job?'?id='+encodeURIComponent(job):''));const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setLoadError('');}catch(e){setLoadError(e instanceof Error?e.message:'Search could not be loaded.');}finally{if(manual)setRefreshing(false);}}
 useEffect(()=>{void load(id);const timer=setInterval(()=>void load(id),4000);return ()=>clearInterval(timer);},[id]);
 async function act(body:Record<string,unknown>){setBusy(true);setAction(String(body.action));setMessage(body.action==='start'?'Starting search…':body.action==='select'?'Adding selected jobs…':'Requesting cancellation…');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);if(body.action==='start'){setId(d.id);setSelected([]);await load(d.id);}else{await load();if(body.action==='select'){setSelected([]);setMessage(`${d.added} new job(s) added to your pipeline. No application was sent.`);}else setMessage('Cancellation requested. Saved results will remain available.');}}catch(e){setMessage(e instanceof Error?e.message:'Search action could not be confirmed.');}finally{setBusy(false);}}
 const run=data?.run,running=run&&['queued','running'].includes(run.status),button='career-control rounded-lg border border-border px-4 py-2 disabled:opacity-50';
 return <section><h2 className="text-2xl font-semibold">Search opportunities</h2><p className="my-3 text-muted">Free public-board scan · Preliminary title ranking · No AI charges. Salary, benefits and remote eligibility need review. Searches continue when you close your phone browser.</p><p className="my-3 text-muted">Configured Greenhouse, Ashby and Lever boards · Up to 10 minutes, 100 boards and 250 saved matches. Broader web-search queries are not run by this scanner.</p><div className="flex flex-wrap gap-3"><button className={button} aria-expanded={showFilters} onClick={()=>setShowFilters(!showFilters)}>View / edit job filters</button><button className={button} aria-expanded={showExisting} onClick={()=>setShowExisting(!showExisting)}>Existing opportunities ({data?.existing?.length||0})</button><button className={button} disabled={busy||!!running} onClick={()=>void act({action:'start',key:crypto.randomUUID()})}>{busy&&action==='start'?'Starting…':'Start free search'}</button>{running&&<button className={button} disabled={busy} onClick={()=>void act({action:'cancel',id:run.id})}>{busy&&action==='cancel'?'Cancelling…':'Cancel search'}</button>}<button className={button} disabled={refreshing} onClick={()=>void load(id,true)}>{refreshing?'Refreshing…':'Refresh results'}</button></div><p role="status" className="my-4 text-brand-text">{message||loadError}</p>
 {showFilters&&<HostedSearchFilters onSaved={()=>void load()}/>}
 {showExisting&&<section className="my-5"><h3 className="text-xl font-semibold">Existing opportunities</h3><p className="my-3 text-muted">Previously found jobs from your pipeline and search history. These are not new matches; current availability, remote eligibility and compensation have not been rechecked.</p><label>Find an opportunity<input aria-label="Find an opportunity" className="my-3 block w-full rounded-lg border border-border bg-surface p-3" value={query} onChange={e=>setQuery(e.target.value)}/></label>{data?.existing?.filter(o=>(o.title+' '+o.company+' '+o.location).toLowerCase().includes(query.toLowerCase())).map(o=><article key={o.url} className="my-3 rounded-xl border border-border p-4"><strong>{o.title}</strong><p>{o.company} · {o.location}</p><p className="my-2 text-muted">{o.status}{o.lastSeen?' · Previously seen '+o.lastSeen:''} · Availability unverified</p><a className="underline text-brand-text" href={o.url} target="_blank" rel="noreferrer">View original posting</a></article>)}{!data?.existing?.length&&<p>No existing opportunities recorded.</p>}</section>}
 {data&&data.jobs.length>0&&<label className="block my-4">Saved searches<select className="block w-full rounded-lg border border-border bg-surface p-3" value={id||data.jobs[0].id} onChange={e=>{setId(e.target.value);setSelected([]);}}>{data.jobs.map(j=><option key={j.id} value={j.id}>{new Date(j.startedAt).toLocaleString()} · {j.status} · {j.offerCount} matches</option>)}</select></label>}
 {run&&<><h3 className="text-xl font-semibold">{run.status[0].toUpperCase()+run.status.slice(1)} · {run.offers.length} new matches</h3>{run.reason&&<p className="my-2">{run.reason}</p>}{run.outdated&&<p className="my-2 text-brand-text">Your profile or job filters changed since this search. Start another search to use current targeting.</p>}<p className="my-3">{run.counts.found} postings found · {run.counts.filtered} filtered by configured rules · {run.counts.duplicates} already known. All saved matches need criteria review.</p><a className="underline text-brand-text" href={endpoint+'?id='+run.id+'&report=1'}>Download search report</a><details className="my-4"><summary>Source coverage ({run.sources.length} reported)</summary>{run.sources.map((s,i)=><p className="my-2" key={i}>{s.company}: {s.status}{s.found!==undefined?` · ${s.found} postings, ${s.matches||0} matches`:''}{s.error?` · ${s.error}`:''}{s.filters?` · Excluded: ${Object.entries(s.filters).filter(([,n])=>n>0).map(([key,n])=>`${key} ${n}`).join(', ')||'none'}`:''}{s.url&&<a className="ml-2 underline text-brand-text" href={s.url} target="_blank" rel="noreferrer">Open employer careers</a>}</p>)}</details><button className={button} disabled={busy||!!running||!selected.length} onClick={()=>void act({action:'select',id:run.id,ids:selected})}>{busy&&action==='select'?'Adding jobs…':`Add selected jobs to pipeline (${selected.length})`}</button><p className="my-2 text-muted">{running?'Wait for this search to finish before adding jobs.':!selected.length?'Select one or more matches to add them to Pipeline.':''}</p>
 {run.offers.map((o,i)=><article key={o.id} className="my-4 rounded-xl border border-border p-4"><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 h-5 w-5 shrink-0" disabled={!!running||run.selected.includes(o.id)} checked={run.selected.includes(o.id)||selected.includes(o.id)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,o.id]:prev.filter(x=>x!==o.id))}/><span><strong>#{i+1} {o.title}</strong><br/>{o.company} · {o.location}</span></label><p className="my-2">Preliminary title fit: {o.fit?.band||'unknown'}{run.selected.includes(o.id)?' · Added to pipeline':''}</p><p className="my-2">{o.salary?`Advertised compensation: ${o.salary.currency||''} ${o.salary.min??'?'}–${o.salary.max??'?'}; verify location and base-pay applicability.`:'Compensation unknown'}</p><p className="my-2 text-muted">Needs verification: {o.unknown.join(', ')}. Source: {o.source}.{o.retrievedAt?` Retrieved ${new Date(o.retrievedAt).toLocaleString()}.`:null}</p><a className="underline text-brand-text" href={o.url} target="_blank" rel="noreferrer">View original posting</a></article>)}{!running&&!run.offers.length&&<p className="my-4">No new matches saved. Previously found jobs are suppressed as duplicates; open Existing opportunities to review them. Check source coverage and job filters before concluding no suitable jobs exist.</p>}</>}
 </section>;
}
