"use client";
import {useEffect,useState} from 'react';
type Opportunity={url:string;title:string;company:string;location:string;status:string;lastSeen:string|null;reviewNotes?:string};
const endpoint=(process.env.NEXT_PUBLIC_HOSTED_BASE||'')+'/api/hosted/search';
export function HostedPipeline(){
 const [refreshing,setRefreshing]=useState(false);
 const [jobs,setJobs]=useState<Opportunity[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[updated,setUpdated]=useState('');
 async function load(manual=false){if(manual)setRefreshing(true);try{const r=await fetch(endpoint,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setJobs(d.existing||[]);setError('');setUpdated(new Date().toLocaleTimeString());}catch(e){setError(e instanceof Error?e.message:'Pipeline could not be refreshed.');}finally{if(manual)setRefreshing(false);}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),10000);const focus=()=>void load();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);};},[]);
 const shown=jobs.filter(o=>(o.title+' '+o.company+' '+o.location+' '+o.status).toLowerCase().includes(query.toLowerCase()));
 return <section><h2 className="text-2xl font-semibold">Pipeline</h2><p className="my-3 text-muted">Saved opportunities from the live VPS pipeline and earlier search history. Jobs added in Search appear here automatically. Previously processed means reviewed earlier; it does not mean an application was sent.</p><p className="my-3 text-muted">Availability, compensation and eligibility need review. Use Search → Saved searches for run history and Applications for evaluated application records.</p><button className="career-control rounded-lg border border-border px-4 py-2" disabled={refreshing} onClick={()=>void load(true)}>{refreshing?'Refreshing…':'Refresh pipeline'}</button><p role="status" className="my-3">{error||`Showing ${shown.length} of ${jobs.length} saved opportunities${updated?' · Refreshed '+updated:''}`}</p><label>Find saved opportunities<input aria-label="Find saved opportunities" className="my-3 block w-full rounded-lg border border-border bg-surface p-3" value={query} onChange={e=>setQuery(e.target.value)}/></label>{shown.map(o=><article key={o.url} className="my-4 rounded-xl border border-border p-4"><h3 className="text-lg font-semibold">{o.title}</h3><p>{o.company} · {o.location}</p><p className="my-2 text-muted">{o.status}{o.lastSeen?' · Previously seen '+o.lastSeen:''} · Availability unverified</p>{o.reviewNotes&&<p className="my-3 whitespace-pre-wrap">Review notes: {o.reviewNotes}</p>}<a className="underline text-brand-text" href={o.url} target="_blank" rel="noreferrer">View original posting</a></article>)}{!error&&!shown.length&&<p className="my-4">No saved opportunities match this view. Add jobs from Search or clear the filter.</p>}</section>;
}
