"use client";
import {useEffect,useState} from 'react';import ReactMarkdown from 'react-markdown';import remarkGfm from 'remark-gfm';
import {HostedDocumentActions} from './hosted-document-actions';
type Doc={id:string;path:string;source:'current'|'archive';type:string;modifiedAt:string;size:number;extension:string;href?:string;snapshotAt?:string};
const endpoint=(process.env.NEXT_PUBLIC_HOSTED_BASE||'')+'/api/hosted/documents';
export function HostedDocuments(){
 const [working,setWorking]=useState('');
 const [docs,setDocs]=useState<Doc[]>([]),[query,setQuery]=useState(''),[source,setSource]=useState('all'),[type,setType]=useState('all'),[since,setSince]=useState(''),[message,setMessage]=useState(''),[archiveAvailable,setArchiveAvailable]=useState(false),[preview,setPreview]=useState<{path:string;extension:string;text:string|null}|null>(null);
 async function load(manual=false){if(manual)setWorking('Refreshing documents…');try{const r=await fetch(endpoint,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setDocs(d.documents);setArchiveAvailable(d.archiveAvailable);setMessage(d.omitted?`${d.omitted} unavailable or restricted file(s) omitted.`:'');}catch(e){setMessage(e instanceof Error?e.message:'Library could not be loaded.');}finally{if(manual)setWorking('');}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000),focus=()=>void load();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);};},[]);
 async function view(d:Doc){setWorking('Opening document…');try{const r=await fetch(endpoint+'?id='+d.id),p=await r.json();if(!r.ok)throw new Error(p.error);setPreview(p);}catch(e){setMessage(e instanceof Error?e.message:'Document could not be opened.');}finally{setWorking('');}}
 const visible=docs.filter(d=>(source==='all'||d.source===source)&&(type==='all'||d.type===type)&&d.path.toLowerCase().includes(query.toLowerCase())&&(!since||new Date(d.modifiedAt)>=new Date(since+'T00:00:00')));
 const input='w-full rounded-lg border border-border bg-surface p-3',button='career-control rounded-lg border border-border px-4 py-2';
 return <section><h2 className="text-2xl font-semibold">Documents</h2><p className="my-3 text-muted">Current files come directly from this workspace on the VPS. New reports and saved edits appear automatically. Archives are dated copies; daily backups are for recovery and are not library documents.</p><div className="grid gap-3 md:grid-cols-2"><label>Find documents<input aria-label="Find documents" className={input} value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Document source<select aria-label="Document source" className={input} value={source} onChange={e=>setSource(e.target.value)}><option value="all">Current and archives</option><option value="current">Current VPS documents</option><option value="archive">Archived snapshot documents</option></select></label><label>Document type<select aria-label="Document type" className={input} value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option>{[...new Set(docs.map(d=>d.type))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Modified on or after<input aria-label="Modified on or after" type="date" className={input} value={since} onChange={e=>setSince(e.target.value)}/></label></div><div className="my-4 flex flex-wrap gap-3"><button className={button} disabled={!!working} onClick={()=>void load(true)}>{working==='Refreshing documents…'?working:'Refresh documents'}</button><button className={button} onClick={()=>{const d=new Date();setSince(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`);setSource('current');}}>Today’s current documents</button><button className={button} onClick={()=>{setSince('');setSource('all');setType('all');setQuery('');}}>Show all documents</button></div><p role="status" className="my-3">{working||message||`${visible.length} documents shown`}</p>{!archiveAvailable&&<p className="my-3">Archive index is not available yet. The archived document page remains accessible from the workspace header.</p>}
 {preview&&<section className="my-5 rounded-xl border border-border p-4"><h3 className="break-all text-xl font-semibold">{preview.path}</h3><button className={button+' my-3'} onClick={()=>setPreview(null)}>Close document preview</button>{preview.text!==null?(preview.extension==='md'?<article className="report-prose break-words"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{img:()=> <span>[Image omitted from text preview]</span>}}>{preview.text}</ReactMarkdown></article>:<pre className="max-h-[70vh] overflow-auto whitespace-pre-wrap break-words text-sm">{preview.text}</pre>):<p>Download the original file below to open this format.</p>}{preview.extension==='html'&&<p className="my-3">HTML is shown as source text. Download the original file to view its layout.</p>}</section>}
 {visible.map(d=><article key={d.id} className="my-3 rounded-xl border border-border p-4"><h3 className="break-all font-semibold">{d.path}</h3><p className="my-2 text-muted">{d.source==='current'?'Current VPS document':'Archived snapshot'} · {d.type} · {d.extension.toUpperCase()} · {Math.ceil(d.size/1024)} KB</p><p className="my-2 text-muted">Modified {new Date(d.modifiedAt).toLocaleString()}{d.snapshotAt?' · Snapshot '+d.snapshotAt:''}</p><div className="flex flex-wrap gap-3">{d.source==='current'?<><button className={button} disabled={!!working} onClick={()=>void view(d)}>View document</button><a className={button} href={endpoint+'?id='+d.id+'&download=1'}>Download original</a></>:<><a className={button} href={d.href?.replace('/files/','/view/')+'.html'} target="_blank" rel="noreferrer">View archived document</a><a className={button} href={d.href} target="_blank" rel="noreferrer">Download archived original</a></>}</div><HostedDocumentActions doc={d} documents={docs} onSaved={()=>void load()}/></article>)}{!visible.length&&<p className="my-4">No documents match these filters. Choose Show all documents to see current files and archives.</p>}</section>;
}
