"use client";
import {useEffect,useState} from 'react';
const endpoint=(process.env.NEXT_PUBLIC_HOSTED_BASE||'')+'/api/hosted/search';
const labels:Record<string,string>={include:'Include title keywords',exclude:'Exclude title keywords',allow:'Allowed location keywords',block:'Blocked location keywords',alwaysAllow:'Location exceptions (override blocked locations)',hardBlock:'Always blocked locations (override exceptions)',contentInclude:'Include description keywords',contentExclude:'Exclude description keywords'};
type Settings={advanced:string;revision:string;fields:Record<string,string>;otherFilters:Record<string,unknown>;locationStrict:boolean;queryCount:number};
export function HostedSearchFilters({onSaved}:{onSaved:()=>void}){
 const [loading,setLoading]=useState(false);
 const [advanced,setAdvanced]=useState('');
 const [settings,setSettings]=useState<Settings|null>(null),[fields,setFields]=useState<Record<string,string>>({}),[history,setHistory]=useState<{id:string;at:string}[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);try{const r=await fetch(endpoint+'?filters=1');const d=await r.json();if(!r.ok)throw new Error(d.error);setSettings(d.settings);setFields(d.settings.fields);setAdvanced(d.settings.advanced);setHistory(d.history);setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Could not load filters.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(restore?:string){setBusy(true);try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'filters',revision:settings?.revision,fields,advanced,restore})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();setMessage(restore?'Filters restored. The previous version is backed up.':'Filters saved. The previous version is backed up. Start another search to use these rules.');onSaved();}catch(e){setMessage(e instanceof Error?e.message:'Save could not be confirmed. Your unsaved edits are retained.');}finally{setBusy(false);}}
 const button='career-control rounded-lg border border-border px-4 py-2 disabled:opacity-50';
 return <section className="my-5 rounded-xl border border-border p-4"><h3 className="text-xl font-semibold">Job filters</h3><p className="my-3 text-muted">One keyword per line. Titles must match an included keyword and no excluded keyword. Locations use the rules below; an explicit Remote keyword does not prove eligibility or travel limits. Empty allowed locations admit all locations except blocked ones.</p>{settings&&<><div className="grid gap-4 md:grid-cols-2">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea aria-label={label} disabled={busy||loading} rows={5} className="mt-2 w-full rounded-lg border border-border bg-surface p-3" value={fields[key]||''} onChange={e=>setFields(prev=>({...prev,[key]:e.target.value}))}/></label>)}</div><p className="my-3 text-muted">Other configured filters are preserved. Missing-location strict mode: {settings.locationStrict?'on':'off'}.</p><details className="my-3"><summary>Other configured rules</summary><p className="my-3 text-muted">Optional advanced rules for salary, posting age, eligibility, visa and trust. YAML format; unknown compensation continues to require review. Leave existing rules intact unless you intend to change them.</p><textarea aria-label="Advanced job filters" disabled={busy||loading} rows={8} className="w-full rounded-lg border border-border bg-surface p-3 font-mono text-sm" value={advanced} onChange={e=>setAdvanced(e.target.value)}/></details><div className="flex flex-wrap gap-3"><button className={button} disabled={busy||loading} onClick={()=>void save()}>{busy?'Saving…':'Save filters'}</button><button className={button} disabled={busy||loading} onClick={()=>void load()}>{loading?'Loading filters…':'Reload filters (replace unsaved edits)'}</button></div><details className="my-4"><summary>Previous filter versions ({history.length})</summary>{history.map(h=><button className={button+' m-2'} disabled={busy||loading} key={h.id} onClick={()=>void save(h.id)}>Restore filters from {new Date(h.at).toLocaleString()}</button>)}</details></>}<p role="status" className="my-3">{loading?'Loading filters…':message}</p></section>;
}
