"use client";
import {useEffect,useState} from 'react';
import {HostedAssistant} from './hosted-assistant';
import {HostedDocuments} from './hosted-documents';
import {HostedPipeline} from './hosted-pipeline';
import {HostedSearch} from './hosted-search';
import ReactMarkdown from 'react-markdown';import remarkGfm from 'remark-gfm';
type App={n:string;company:string;role:string;status:string;notes:string};
type State={candidate:string;revision:string;trackerRevision:string;contents:Record<string,string>;profile:Record<string,any>;states:string[];applications:App[];migrationNeeded:boolean;migration:{proposed:string;removed:string[]}|null};
const api=(suffix='')=>(process.env.NEXT_PUBLIC_HOSTED_BASE||'')+'/api/hosted'+suffix;
const labels:Record<string,string>={name:'Full name',email:'Email',phone:'Phone',location:'Location',roles:'Target roles (one per line)',minimum:'Minimum annual base salary',target:'Target annual base salary or range',currency:'Currency',remote:'Remote and travel policy',authorization:'Work authorization',citizenship:'Citizenship (if supplied)'};
export function HostedWorkspace(){
 const [profileDirty,setProfileDirty]=useState(false),[cvDirty,setCvDirty]=useState(false),[loading,setLoading]=useState('');
 const [state,setState]=useState<State|null>(null),[tab,setTab]=useState('profile'),[message,setMessage]=useState(''),[cv,setCv]=useState(''),[narrative,setNarrative]=useState(''),[fields,setFields]=useState<Record<string,string>>({}),[sponsor,setSponsor]=useState(false),[pending,setPending]=useState(false),[statuses,setStatuses]=useState<Record<string,string>>({}),[note,setNote]=useState<Record<string,string>>({}),[history,setHistory]=useState<{id:string;at:string;operation:string}[]>([]),[restore,setRestore]=useState<{id:string;contents:Record<string,string>}|null>(null);
 async function load(){setLoading('Loading current files…');try{const res=await fetch(api());const d=await res.json();if(!res.ok){setMessage(d.error);return;}setStatuses({});setNote({});setState(d);setCv(d.contents['cv.md']);setNarrative(d.contents['modes/_profile.md']);const p=d.profile;setFields({name:p.candidate?.full_name||'',email:p.candidate?.email||'',phone:p.candidate?.phone||'',location:p.candidate?.location||'',roles:(p.target_roles?.primary||[]).join('\n'),minimum:p.compensation?.minimum||'',target:p.compensation?.target_range||'',currency:p.compensation?.currency||'',remote:p.compensation?.location_flexibility||'',authorization:p.location?.visa_status||'',citizenship:p.location?.citizenship||''});setSponsor(p.location?.needs_sponsorship===true);setProfileDirty(false);setCvDirty(false);}catch{setMessage('Current files could not be loaded. Your text is retained.');}finally{setLoading('');}}
 useEffect(()=>{void load();const view=new URLSearchParams(window.location.search).get('view');if(view&&['profile','cv','search','documents','assistant','pipeline','tracker','history'].includes(view))setTab(view);},[]);
 async function send(body:Record<string,unknown>){setPending(true);setMessage('Saving…');try{const res=await fetch(api(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,revision:state?.revision})});const d=await res.json();if(!res.ok){setMessage(d.error+' Your unsaved text is still here.');return;}setMessage(body.action==='tracker'?'Application update saved. The previous tracker version is backed up.':'Saved. The previous version is backed up in Profile/CV recovery.');if(body.action==='tracker'){const r=await fetch(api());const fresh=await r.json();if(!r.ok)throw new Error('Refresh failed');setState(previous=>previous?{...previous,applications:fresh.applications,trackerRevision:fresh.trackerRevision}:previous);const n=String(body.n);setNote(previous=>({...previous,[n]:''}));setStatuses(previous=>{const next={...previous};delete next[n];return next;});}else if(body.action==='restore'){await load();setRestore(null);}else{setState(previous=>previous?{...previous,revision:d.revision,contents:d.contents,profile:d.profile,migrationNeeded:false}:previous);if(body.action==='profile'){setNarrative(d.contents['modes/_profile.md']);setProfileDirty(false);}if(body.action==='cv')setCvDirty(false);}}catch{setMessage('Save could not be confirmed. Reload and compare before retrying; your text is retained.');}finally{setPending(false);}}
 const button='career-control rounded-lg border border-border px-4 py-2 hover:bg-surface-hover disabled:opacity-50';const input='w-full rounded-lg border border-border bg-surface p-3 text-foreground';
 if(!state)return <div className="p-8">{message||'Loading workspace…'}</div>;
 return <div className="hosted-workspace mx-auto max-w-6xl px-5 py-8"><header><a href={`/${state.candidate}/`} className="text-brand-text">← Archived documents (dated snapshot)</a><h1 className="mt-3 text-3xl font-semibold">{state.candidate==='brad'?'Brad':'Steve'}’s live workspace</h1><p className="mt-2 text-muted">VPS is authoritative · Shared login · Profile editing and free search · No automatic submissions</p></header><nav className="my-6 flex flex-wrap gap-3">{['profile','cv','search','documents','assistant','pipeline','tracker','history'].map(t=><button key={t} className={button} aria-current={tab===t?'page':undefined} onClick={async()=>{setTab(t);if(t==='history'){setLoading('Loading recovery history…');try{const r=await fetch(api('?history=1'));if(!r.ok)throw new Error();setHistory(await r.json());}catch{setMessage('Recovery history could not be loaded.');}finally{setLoading('');}}}}>{t==='cv'?'CV':t==='history'?'Profile/CV recovery':t==='tracker'?'Applications':t[0].toUpperCase()+t.slice(1)}</button>)}<a className={button} href={api('?export=1')}>Download backup/export</a></nav><div role="status" className="mb-4 whitespace-pre-wrap text-brand-text">{loading||message}</div>
 {tab==='search'&&<HostedSearch/>}
 {tab==='pipeline'&&<HostedPipeline/>}
 {tab==='documents'&&<HostedDocuments/>}
 {tab==='assistant'&&<HostedAssistant/>}
 {tab==='profile'&&<section><h2 className="text-2xl font-semibold">Profile</h2><p className="my-3 text-muted">Saving automatically backs up the previous version and keeps targeting consistent. Edits preserve unrelated fields. Base pay excludes bonus, equity and benefits. Changes do not rewrite your CV or dated application samples.</p><div className="grid gap-4 md:grid-cols-2">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea disabled={pending} className={input} rows={key==='roles'||key==='remote'?4:2} value={fields[key]||''} onChange={e=>{setFields({...fields,[key]:e.target.value});setProfileDirty(true);}}/></label>)}</div><label className="my-4 block"><input type="checkbox" disabled={pending} checked={sponsor} onChange={e=>{setSponsor(e.target.checked);setProfileDirty(true);}}/> Employer sponsorship required</label><details><summary>Personalization narrative (managed targeting is regenerated on save)</summary><textarea disabled={pending} className={input+' mt-3 min-h-80'} value={narrative} onChange={e=>{setNarrative(e.target.value);setProfileDirty(true);}}/></details><details className="my-4"><summary>Preview profile changes</summary><pre className="whitespace-pre-wrap">{Object.entries(fields).map(([k,v])=>`${labels[k]}: ${v}`).join('\n\n')}</pre></details><button className={button} disabled={pending} onClick={()=>void send({action:'profile',fields:{...fields,sponsorship:sponsor},narrative})}>{pending?'Saving…':'Save profile'}</button><p role="status" className="my-3 text-muted">{profileDirty?'Unsaved profile changes':'Profile matches saved version'}</p></section>}
 {tab==='cv'&&<section><h2 className="text-2xl font-semibold">Master CV</h2><p className="my-3 text-muted">Only save facts you can support. This editor does not generate claims or update application samples.</p><div className="grid gap-4 lg:grid-cols-2"><textarea disabled={pending} aria-label="Master CV text" className={input+' min-h-[60vh] font-mono text-sm'} value={cv} onChange={e=>{setCv(e.target.value);}}/><article className="report-prose rounded-xl border border-border p-5"><ReactMarkdown remarkPlugins={[remarkGfm]}>{cv}</ReactMarkdown></article></div><button className={button+' mt-4'} disabled={pending} onClick={()=>void send({action:'cv',content:cv})}>{pending?'Saving…':'Save CV'}</button><p role="status" className="my-3 text-muted">{cvDirty?'Unsaved CV changes':'CV matches saved version'}</p></section>}
 {tab==='tracker'&&<section><h2 className="text-2xl font-semibold">Existing applications</h2><p className="my-3 text-muted">Updating status records an event you confirm; it does not send an application. Notes append to the existing record.</p>{state.applications.map(a=><div key={a.n} className="my-4 rounded-xl border border-border p-5"><h3 className="text-lg font-semibold">#{a.n} {a.company} — {a.role}</h3><p className="my-2 whitespace-pre-wrap text-muted">{a.notes}</p><select aria-label={`Status for ${a.company}`} className={input} value={statuses[a.n]||a.status} onChange={e=>setStatuses({...statuses,[a.n]:e.target.value})}>{state.states.map(s=><option key={s}>{s}</option>)}</select><textarea disabled={pending} className={input+' mt-3'} aria-label={`Append note for ${a.company}`} placeholder="Add a note (existing notes remain)" value={note[a.n]||''} onChange={e=>setNote({...note,[a.n]:e.target.value})}/><button className={button+' mt-3'} disabled={pending} onClick={()=>void send({action:'tracker',n:a.n,status:statuses[a.n]||a.status,note:note[a.n]||'',trackerRevision:state.trackerRevision})}>{pending?'Saving…':'Save update'}</button></div>)}</section>}
 {tab==='history'&&<section><h2 className="text-2xl font-semibold">Profile/CV recovery</h2><p className="my-3 text-muted">This is edit recovery, not search history. Find searches in Search → Saved searches and saved jobs in Pipeline. Restoring creates a new revision and keeps current content recoverable. Actions are attributed to the shared login, not a verified individual.</p>{history.map(h=><button key={h.id} className={button+' mr-3 mt-3'} onClick={async()=>{setLoading('Opening revision…');try{const r=await fetch(api('?history=1&id='+encodeURIComponent(h.id)));if(!r.ok)throw new Error();setRestore(await r.json());}catch{setMessage('Revision could not be opened.');}finally{setLoading('');}}}>{h.at} · before {h.operation}</button>)}{restore&&<div className="mt-5"><details open><summary>Preview restore</summary>{Object.entries(restore.contents).map(([f,t])=><div key={f}><h3 className="my-3 font-semibold">{f}</h3><pre className="max-h-80 overflow-auto whitespace-pre-wrap text-sm">{t}</pre></div>)}</details><button className={button+' mt-4'} disabled={pending} onClick={()=>{if(confirm('Restore these profile/CV files as a new revision?'))void send({action:'restore',id:restore.id});}}>{pending?'Restoring…':'Restore reviewed revision'}</button></div>}</section>}
 <footer className="mt-10 text-sm text-muted">Revision {state.revision.slice(0,12)} · Live Documents, Search, Pipeline and Applications read VPS files directly; no manual sync is needed. Archived documents and Mac backups are dated copies. On a conflict, copy unsaved text before reloading. <button className="career-control underline" disabled={!!loading||pending} onClick={()=>{if(confirm('Reload and replace your unsaved editor text with current VPS files?'))void load();}}>Reload current files</button></footer></div>;
}
